### ISSUE TITLE
Disable unsecure ssl values (option or static)

### ISSUE THREAD

**Issue by MaStr** [lefcha/imapfilter#100]
Hi,
thank you for that handy tool!

Would it be possible to create an option value for the SSL options or 
disable the old SSLv2 and SSLv3 stuff statically in the code?

For various security reason, they are known as "broken".

best regards
  Matthias

**Comment by larryhynes** [comment]
You can put a value for `ssl` in the Accounts section of your `config.lua`. From the man page of `imapfilter_config`:

```
ssl     Forces an imaps connection and specifies the SSL/TLS protocol/version to be used. 
It takes a string as a value, specifically one of: ``ssl3'', ``ssl23'', ``tls1'', ``tls1.1'', ``tls1.2''.
```

**Comment by MaStr** [comment]
oh f***, you are right!
 I overread that and was a bit over-motivated yesterday.

Sorry, I close that thing here.
