### ISSUE TITLE
daemon and require

### ISSUE THREAD

**Issue by mathomp4** [lefcha/imapfilter#103]
All,

I'm betting this is a FAQ, but my search-fu is failing me. Namely, I keep around two config files for my imapfilter setup. One is a version that doesn't run a daemon but that I can run interactively with verbosity, and my main config is the one that becomes a daemon. Now, in both cases, I have a *lot* of rules, and they both used to duplicate each other. So, I looked around at Lua and saw the "require" function. In the end, I put all my rules in a file (configrules.lua) and made my main config.lua look like:

```lua
-- Add to package path --

package.path = "/home/user/.imapfilter/?.lua;" .. package.path

-- OPTIONS --
options.timeout = 240
options.subscribe = true
options.starttls = true

-- This one is whether a message is expunged from
-- the mailbox after moving...I think.  Set to false
-- to prevent this.
--options.expunge = false

-- Get the password
password = get_password('Enter password: ')

function sortMail()
   -- ACCOUNTS --
   account = IMAP {
       server = 'myserver',
       username = "user",
       password = password,
       ssl = 'tls2',
   }

   -- Sorting Rules --

   require "configrules"
   
end

become_daemon(600, sortMail)
```

Now, if you delete the function, end, and become_daemon, this file is my config-nodaemon.lua file. 

My issue is that this works...once. That is, if I run it without being a daemon, it works fine. If I run it as a daemon it runs the first time, but then never again (aka, my mail doesn't move). Am I missing a simple flag/call/something somewhere to allow me to do this? (The fact that the nodaemon works as expected makes me think I at least have valid Lua code, but maybe not?)

**Comment by lefcha** [comment]
The use of `require` is purposed for loading Lua modules, not executing a file, and thus it probably only works the first time, because Lua considers the module with that name as already loaded.

Instead try with:

```lua
dofile "configrules.lua"
```

**Comment by lefcha** [comment]
Also, you don't need to set up a path for the module loading, you can just specify the path to your `configrules.lua` file directly to `dofile`, for example:

```lua
dofile '/path/to/configrules.lua'
```
