### ISSUE TITLE
imapfilter enter_idle() failure

### ISSUE THREAD

**Issue by fm2802** [lefcha/imapfilter#104]
C (5): 125E IDLE
imapfilter: reading data through SSL; Operation timed out
imapfilter: idle request to user@mail.company.com failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/usr/local/share/imapfilter/mailbox.lua:46: in field '_check_result'
	/usr/local/share/imapfilter/mailbox.lua:1045: in method 'enter_idle'
	/Users/user/.imapfilter/config.lua:81: in main chunk

line 81 is: until not (company.Inbox:enter_idle())

IMAPFilter 2.5.7

**Comment by lefcha** [comment]
Try setting `options.keepalive` to a lower setting than the default of `29` minutes, as it seems that the server timeouts earlier than that.  You can try setting it to `19` or even `9`.

**Comment by fdemello** [comment]
According to http://manpages.ubuntu.com/manpages/hardy/man5/imapfilter_config.5.html, the default is 120 (in seconds) which is what I have configured. Is that not the case?

**Comment by lefcha** [comment]
That is the `options.timeout` and its default value is `120` seconds, and it's a totally different option than `options.keepalive`.  Try lowering `options.keepalive`...

**Comment by fdemello** [comment]
That fixed it, thanks!
