### ISSUE TITLE
Feature request - case insensitive regex matching

### ISSUE THREAD

**Issue by mc0e** [lefcha/imapfilter#107]
The subject line pretty much says it.  I'd like to be able to use functions like `body_match()` in a case insensitive manner without needing `[Tt][Hh][Ii][Ss]` sort of stuff.

**Comment by lefcha** [comment]
You can do that by using the `(?i)` in front of your `pattern` argument.  For example for `match_body()` you would use:
```lua
match_body('(?i)this')
```

You can even turn the case-less mode on, and then off with `(?-i)`, for example to match `[Tt][Hh][Ii][Ss]that` you would do:

```lua
match_body('(?i)this(?-i)that')
```
More on that here: http://www.pcre.org/original/doc/html/pcrepattern.html#SEC13

**Comment by mc0e** [comment]
OK, this solves the issue for me.  It might be worth pointing out in the documentation though?

The use of PCRE is only specified in the imapfilter_config man page under the regex_search function.  IT could be a bit more clearly sign-posted.

`man imapfilter_config` has some examples of function usage including regex_search.  Perhaps it could be modified to something that demonstrates the case insensitive match.  

e.g.:

    success, capture = regex_search('^(?i)pcre: (\\w)$', 'mystring')

**Comment by lefcha** [comment]
Good idea, thanks!

I just pushed a commit that clarifies the use of PCRE in the `match_*()` methods, adds a better example of `regex_search()` that includes the insensitive match modifier, and links to the relevant PCRE documention in the `SEE ALSO` section.

**Comment by lefcha** [comment]
Closed by 1384fb7d3a4c05a57f3dbc49e957de5a73da1ac1.
