### ISSUE TITLE
HowTo - Compile from source on Broadcom router

### ISSUE THREAD

**Issue by elvisimprsntr** [lefcha/imapfilter#108]
I am using imapfilter to snort emails to invoke home automation commands on a Linux server.  I would like to compile imapfilter on a Broadcom based router.   I know how to install optware and lua on the router.  

Can I compile imapfilter from source without modification on a Broadcom router?
If not what modifications are necessary?

**Comment by lefcha** [comment]
Well if the router has a POSIX compiler and C library, the Lua libs, the OpenSSL library and the PCRE library, you should be able to compile imapfilter without modifications.

Let me know how that went, I would be really interested to know... And if you face any problems, share it here, and maybe we can solve them.

**Comment by elvisimprsntr** [comment]
I gave it a go, but i've already upgraded all my router to DD-WRT K3 builds which do not have support for optware packages yet. :(   

Time to dust off my RPi...

**Comment by elvisimprsntr** [comment]
FYI. Got IPAMFILTER installed and working on a RPi.   https://github.com/elvisimprsntr/ifttt-imapfilter

DD-WRT will have to wait until K3 builds get support for optware packages.
