### ISSUE TITLE
IMAP4 / Exchange 2013 support

### ISSUE THREAD

**Issue by fdemello** [lefcha/imapfilter#109]
My imapfilter stopped working after the server was upgraded to Exchange 2013. Any ideas why? Here's the code.

emails =  (mailbox.Inbox:contain_to('user') +
             mailbox.Inbox:contain_from('user') +
         mailbox.Inbox:contain_cc('user'))*
           (mailbox.Inbox:match_subject('condition1') -
            mailbox.Inbox:match_subject('condition2') -
            mailbox.Inbox:match_subject('condition3'))

mailbox.Inbox:fetch_fields({ 'subject' }, emails) -> this returns nil

**Comment by lefcha** [comment]
Try executing imapfilter the `-d debug.log`  argument so we can see more details of what is going wrong here.

**Comment by fm2802** [comment]
I cut off some of the text for privacy reasons. I hope this is enough.

log file: '/tmp/imapfilter.log'
getting response (5):

* OK The Microsoft Exchange IMAP4 service is ready.

sending command (5):

1000 NOOP

getting response (5):

1000 OK NOOP completed.

sending command (5):

1001 CAPABILITY

getting response (5):

* CAPABILITY IMAP4 IMAP4rev1 AUTH=...
1001 OK CAPABILITY completed.

sending command (5):

1002 LOGIN "user" *

getting response (5):

1002 OK LOGIN completed.
...

1007 UID SEARCH ALL FROM "user"

getting response (5):

* SEARCH numbers..
1007 OK SEARCH completed.

sending command (5):

1008 UID SEARCH ALL CC "user"

getting response (5):

..

1009 OK SEARCH completed.

sending command (5):

100A UID FETCH 267963 BODY.PEEK[HEADER.FIELDS (Subject)]

getting response (5):

...
 
 * 2 FETCH (BODY[HEADER.FIELDS (Subject)] {23}
Subject: Re: Subject title

 UID 267985)

getting response (5):

100B OK FETCH completed.

sending command (5):

100C UID FETCH 267988 BODY.PEEK[HEADER.FIELDS (Subject)]

getting response (5):


... gets all e-mails ...
 
 
11BF OK FETCH completed.

sending command (5):

11C0 UID FETCH 275653 BODY.PEEK[HEADER.FIELDS (Subject)]

getting response (5):

11C0 NO Some of the requested messages no longer exist.

sending command (5):

11C1 UID FETCH 275669 BODY.PEEK[HEADER.FIELDS (Subject)]

getting response (5):

* 440 FETCH (BODY[HEADER.FIELDS (Subject)] {98}
Subject: subject title

 UID 275669)

getting response (5):

11C1 OK FETCH completed.

sending command (5):

11C2 UID SEARCH ALL


11C2 UID SEARCH ALL

getting response (5):

* SEARCH numbers...

11C2 OK SEARCH completed.

sending command (5):

11C3 OK SEARCH completed.

sending command (5):

11C4 IDLE

getting response (5):

+ IDLE accepted, awaiting DONE command.

getting response (5):

* 439 EXPUNGE
* 437 EXPUNGE
* 434 EXPUNGE
* 433 EXPUNGE
* 432 EXPUNGE
* 425 EXPUNGE
* 434 EXISTS

getting response (5):

* 6 RECENT
* 435 EXISTS

sending continuation data (5):

DONE

getting response (5):

11C4 OK IDLE completed.

**Comment by fm2802** [comment]
If I print emails, as below, 

for k, v in pairs(emails) do
    	print(k)
    	print(v)
end

I get the following results. Is this expected?

match_cc
function: 0x7ff6ebc2d9b0
is_flagged
function: 0x7ff6ebc2d330
arrived_before
function: 0x7ff6ebc2d650
mark_deleted
function: 0x7ff6ebc2cff0
mark_seen
function: 0x7ff6ebc2d080
sent_on
function: 0x7ff6ebc2d6b0
remove_flags
function: 0x7ff6ebc2d0f0
is_recent
function: 0x7ff6ebc2d470
is_new
function: 0x7ff6ebc2d410
contain_bcc
function: 0x7ff6ebc2d800
contain_cc
function: 0x7ff6ebc2d830
arrived_on
function: 0x7ff6ebc2d620
contain_body
function: 0x7ff6ebc2d920
is_unanswered
function: 0x7ff6ebc2d4d0
match_to
function: 0x7ff6ebc2da40
is_newer
function: 0x7ff6ebc2d740
unmark_flagged
function: 0x7ff6ebc2d3e0
unmark_draft
function: 0x7ff6ebc2d3b0
is_undraft
function: 0x7ff6ebc2d530
is_undeleted
function: 0x7ff6ebc2d500
move_messages
function: 0x7ff6ebc2d210
contain_subject
function: 0x7ff6ebc2d890
contain_message
function: 0x7ff6ebc2d950
mark_answered
function: 0x7ff6ebc2d150
is_answered
function: 0x7ff6ebc2d2a0
contain_header
function: 0x7ff6ebc2d8f0
select_all
function: 0x7ff6ebc2d240
match_field
function: 0x7ff6ebc2da70
sent_since
function: 0x7ff6ebc2d710
_new
function: 0x7ff6ebc2c960
is_unflagged
function: 0x7ff6ebc2d560
delete_messages
function: 0x7ff6ebc2d1b0
add_flags
function: 0x7ff6ebc2cea0
sent_before
function: 0x7ff6ebc2d6e0
match_subject
function: 0x7ff6ebc2da10
unmark_answered
function: 0x7ff6ebc2d0b0
is_smaller
function: 0x7ff6ebc2d5f0
match_message
function: 0x7ff6ebc2db00
match_header
function: 0x7ff6ebc2daa0
_mt
table: 0x7ff6ebf51610
mark_draft
function: 0x7ff6ebc2d020
match_from
function: 0x7ff6ebc2d9e0
is_larger
function: 0x7ff6ebc2d5c0
unmark_deleted
function: 0x7ff6ebc2d380
contain_field
function: 0x7ff6ebc2d7d0
match_bcc
function: 0x7ff6ebc2d980
arrived_since
function: 0x7ff6ebc2d680
_difference
function: 0x7ff6ebc2cfc0
is_draft
function: 0x7ff6ebc2d300
_union
function: 0x7ff6ebc2cee0
is_older
function: 0x7ff6ebc2d770
match_body
function: 0x7ff6ebc2dad0
contain_from
function: 0x7ff6ebc2d860
is_unseen
function: 0x7ff6ebc2d590
_type
set
unmark_seen
function: 0x7ff6ebc2d180
replace_flags
function: 0x7ff6ebc2d120
send_query
function: 0x7ff6ebc2d270
mark_flagged
function: 0x7ff6ebc2d050
is_old
function: 0x7ff6ebc2d440
is_deleted
function: 0x7ff6ebc2d2d0
_intersection
function: 0x7ff6ebc2cf90
copy_messages
function: 0x7ff6ebc2d1e0
is_seen
function: 0x7ff6ebc2d4a0
contain_to
function: 0x7ff6ebc2d8c0
has_flag
function: 0x7ff6ebc2d7a0

**Comment by fm2802** [comment]
Hi @lefcha , any ideas?

**Comment by lefcha** [comment]
You can't print searching results like that because they are special tables that contain also all the searching functions in order to do meta-searching.  You can print the results with something like this:

```lua
function print_uids(messages)
    for _, msg in ipairs(messages) do
        mbox, uid = unpack(msg)
        print(mbox._string, uid)
    end
end

print_uids(emails)
```

I suggest you do that in various stages of your filters where you think something is wrong, to verify that you get the correct results.

Other than that, I can't see any errors in the debug log, and the server seems to reply reasonable values to all the requests.

As I see it you are fetching the fields with the old way, and I would suggest using the way that is described since some time in the `imapfilter_config(5)` man page, specifically the `FETCHING` section, because it's simpler to go through the results.

Another question, what version of imapfilter are you using? You can see that with `imapfilter -V`.

**Comment by fm2802** [comment]
I was using 2.5.7 and have now upgraded to 2.6.2. Do you have any examples using the new way? The only page I found was https://github.com/lefcha/imapfilter/blob/master/doc/imapfilter_config.5 and it says to use "fetch_field" which fails for me.

**Comment by lefcha** [comment]
What did the `print_results(email)` return? We need that to see whether you got any messages matching your filters, otherwise it makes no sense to fetch fields for them...

Also with the new way of using `fetch_field()` you do:

```lua
for _, mesg in ipairs(all) do
    mbox, uid = table.unpack(mesg)
    subject = mbox[uid]:fetch_field('subject')
    print(mbox._string, uid, subject)
end
```

With the above example you just print the `Subject` header line for each message, but you can see more examples on how to use the `fetch_*()` methods in the [extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua) file.

**Comment by riverofbass** [comment]
Hi,

I have a similar issue using imapfilter against Office 365. When performing the IMAP command "UID SEARCH ALL TO"  as imapfiler issues, it returns nothing whereas using "UID SEARCH TO" it returns the expected emails (I tested by connecting myself to the IMAP daemon with openssl s_client -connect outlook.office365.com:993 -crlf).

Since this is a corporate account, I asked my company to open an issue to Microsoft support but so far they didn't provide an acceptable answer.

**Comment by lefcha** [comment]
Indeed, this looks like a server bug and filing a problem report was a good step forward.

As a workaround you can modify [mailbox.lua](https://github.com/lefcha/imapfilter/blob/master/src/mailbox.lua#L103), and change `'ALL'` to `''`.  This way imapfilter will not send `ALL` in search requests.

If you don't get anywhere with having this corrected on the server, let me know so I will add an option that will make it possible to disable sending `ALL` in search requests.

**Comment by fm2802** [comment]
After I made this change and re-ran make all, make install I got:

imapfilter: IMAP (3): 1005 BAD Command Argument Error. 11
imapfilter: IMAP (3): 1006 BAD Command Argument Error. 11
imapfilter: search request to myuser@mail.company.com failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/usr/local/share/imapfilter/mailbox.lua:46: in field '_check_result'
	/usr/local/share/imapfilter/mailbox.lua:127: in field '_send_query'
	/usr/local/share/imapfilter/mailbox.lua:519: in function </usr/local/share/imapfilter/mailbox.lua:518>
	(...tail calls...)
	/Users/myuser/.imapfilter/config.lua:42: in main chunk

**Comment by lefcha** [comment]
Can you rerun with `-v` so we can see what exactly are the `1005` and `1006` requests?

**Comment by riverofbass** [comment]
Actually if you put an empty string instead of ALL it will fail because you will have 2 spaces between SEARCH and your criteria.
I use this patch https://gist.github.com/riverofbass/6f956433ae485ae50312 on my imapfilter installation.

**Comment by fm2802** [comment]
$ imapfilter -v
S (3): * OK The Microsoft Exchange IMAP4 service is ready.
C (3): 1000 CAPABILITY
S (3): 1000 OK CAPABILITY completed.
C (3): 1001 LOGIN "myuser" *
S (3): 1001 OK LOGIN completed.
C (3): 1002 CAPABILITY
S (3): 1002 OK CAPABILITY completed.
C (3): 1003 NAMESPACE
S (3): 1003 OK NAMESPACE completed.
Checking for cases in Inbox
C (3): 1004 SELECT "Inbox"
S (3): 1004 OK [READ-WRITE] SELECT completed.
imapfilter: /usr/local/share/imapfilter/mailbox.lua:129: bad argument #2 to 'search' (string expected, got nil)
stack traceback:
	[C]: in ?
	[C]: in field 'search'
	/usr/local/share/imapfilter/mailbox.lua:129: in field '_send_query'
	/usr/local/share/imapfilter/mailbox.lua:523: in function </usr/local/share/imapfilter/mailbox.lua:522>
	(...tail calls...)
	/Users/myuser/.imapfilter/config.lua:48: in main chunk


line 48: 	myEmails = mailbox.Inbox:select_all()

**Comment by lefcha** [comment]
My bad, try with this patch: https://gist.github.com/lefcha/5d5720a2863884397e6f

**Comment by PeterS242** [comment]
@lefcha I am also experiencing this issue.  If I change the 'ALL' to '', my Exchange server receives two spaces in the query and errors on this.  The patch you provide above appears to have expired.  I did a clone just today of the repository, FYI.  Is there perhaps a flag I can set on the connection to switch to "buggy Exchange server mode" because that would be nice.

**Comment by lefcha** [comment]
Can you try with this patch and see if it helps?

https://gist.github.com/lefcha/0c6ced7fb8cf99b8b82bde60fb394e11
