### ISSUE TITLE
no match with contain_from('xx')

### ISSUE THREAD

**Issue by odins-raven** [lefcha/imapfilter#11]
Hi all:

I installed IMAPFilter 2.2.2 on Mac OS X. (Great tool I must say.) I can log into my AOL IMAP account, see mailboxes, etc. Also queries like the following **work perfectly**:

```msgs = myaccount.INBOX:is_flagged()
msgs:move_messages(myaccount.Flagged)

``````

What drives me crazy, though, is that none of the contain_* commands work. For instance,

```msgs = myaccount.INBOX:contain_from('newsletter')
msgs:move_messages(myaccount.Newsletters)
``````

does **not find any match**, even though there are a number of e-mails in the INBOX that have "newsletter" as a substring in the from e-mail address header.

How can I solve the issue?

Thanks for any hint.

BTW, here is the output for "imapfilter -v" running with the 2nd example mentioned above:

```S (3): \* OK IMAP4 ready
C (3): 1000 CAPABILITY
S (3): 1000 OK completed
C (3): 1001 LOGIN "xxx" *
S (3): 1001 OK LOGIN completed
C (3): 1002 NAMESPACE
S (3): 1002 OK NAMESPACE completed
C (3): 1003 SELECT "INBOX"
S (3): 1003 OK [READ-WRITE] SELECT completed
C (3): 1004 UID SEARCH ALL FROM "newsletter"
S (3): 1004 OK SEARCH completed
C (3): 1005 LOGOUT
S (3): 1005 OK LOGOUT completed

```
```

**Comment by lxsli** [comment]
Maybe this could issue a warning? Pretty frustrating that imapfilter continues silently.

**Comment by lefcha** [comment]
This can't be easily done by the client, as the server doesn't report an error back, it just reports back that it didn't find anything, it basically falsifies the real results with an empty result, which is even worse than violating the IMAP protocol specification.  It is indeed frustrating...

**Comment by lxsli** [comment]
Well [image: 💩]. Thanks for the response!
