### ISSUE TITLE
has_flag(): expected atom instead of "end of data"

### ISSUE THREAD

**Issue by ayekaramba** [lefcha/imapfilter#110]
Hi, when using Mailbox:has_flag() to filter for mails that have been marked with a custom flag (e.g. 'MyFlag') I get an error message from the server:

    C (3): 1007 UID SEARCH ALL KEYWORD "MyFlag"
    S (3): 1007 BAD expected atom instead of "end of data"
    imapfilter: IMAP (3): 1007 BAD expected atom instead of "end of data"

Without the quotes from the command string the command succeeds:

    C (3): 1007 UID SEARCH ALL KEYWORD MyFlag
    S (3): 1007 OK UID SEARCH completed

Is this a bug in Imapfilter or is there a problem with the IMAP server of my mail provider GMX?
Thanks in advance!

**Comment by lefcha** [comment]
You are right, the double quotation shouldn't be there.  Thank you very much for reporting this!

**Comment by lefcha** [comment]
Closed by e2a1af0dbe7d52989b9191a82f6641bb46903b0b.
