### ISSUE TITLE
Compile on OmniOS (illumos)

### ISSUE THREAD

**Issue by dewi-ny-je** [lefcha/imapfilter#111]
Hello, I have the various dependencies installed and I would like to install imapfilter on OmniOS r151014. It is based on illumos kernel, derivative from OpenSolaris.

$ ls /usr/lib/libcr*
/usr/lib/libcrle.so.1        /usr/lib/libcrypt_i.so
/usr/lib/libcrypt.so         /usr/lib/libcrypt_i.so.1
/usr/lib/libcrypt.so.1       /usr/lib/libcrypto.so
/usr/lib/libcrypt_d.so       /usr/lib/libcrypto.so.0.9.8
/usr/lib/libcrypt_d.so.1     /usr/lib/libcrypto.so.1.0.0
$ ls /usr/lib/libpcre*
/usr/lib/libpcre.so             /usr/lib/libpcrecpp.so.0.0.0
/usr/lib/libpcre.so.1           /usr/lib/libpcreposix.so
/usr/lib/libpcre.so.1.2.3       /usr/lib/libpcreposix.so.0
/usr/lib/libpcrecpp.so          /usr/lib/libpcreposix.so.0.0.2
/usr/lib/libpcrecpp.so.0
$ ls /usr/local/lib/liblua*
/usr/local/lib/liblua.a
$ ls /usr/lib/libssl*
/usr/lib/libssl.so        /usr/lib/libssl.so.0.9.8  /usr/lib/libssl.so.1.0.0
$ which lua
/usr/local/bin/lua

I put the dirs in the Makefile:
INCDIRS = -I/usr/local/include -I/usr/include
LIBDIRS = -L/usr/local/lib -L/usr/lib

and I exported the paths for GNU stuff:
$ echo $PATH
/usr/gnu/bin/:/opt/gcc-4.8.1/bin/:/usr/bin:/bin:/usr/local/bin:/usr/sbin:/opt/omni/bin/

but I get:
$ make
cd src && make all
make[1]: Entering directory `/export/home/olaf/src/imapfilter-master/src'
gcc -o imapfilter -L/usr/local/lib -L/usr/lib  auth.o buffer.o cert.o core.o file.o imapfilter.o list.o log.o lua.o memory.o misc.o namespace.o pcre.o regexp.o request.o response.o session.o signal.o socket.o system.o -lm -ldl -llua -lpcre -lssl -lcrypto
Undefined                       first referenced
 symbol                             in file
socket                              socket.o  (symbol belongs to implicit dependency usr/lib/libsocket.so.1)
connect                             socket.o  (symbol belongs to implicit dependency /usr/lib/libsocket.so.1)
getaddrinfo                         socket.o  (symbol belongs to implicit dependency /usr/lib/libsocket.so.1)
freeaddrinfo                        socket.o  (symbol belongs to implicit dependency /usr/lib/libsocket.so.1)
gai_strerror                        socket.o  (symbol belongs to implicit dependency /usr/lib/libsocket.so.1)
ld: fatal: symbol referencing errors. No output written to imapfilter
collect2: error: ld returned 1 exit status
make[1]: *** [imapfilter] Error 1
make[1]: Leaving directory `/export/home/olaf/src/imapfilter-master/src'
make: *** [all] Error 2

Could you help me? thanks

**Comment by lefcha** [comment]
Hm, maybe try with `make MYLIBS=-lsocket -liconv`.

**Comment by dewi-ny-je** [comment]
I haven't tried it but it compiles and runs with only MYLIBS=-lsocket
Thanks! Maybe it's worth mentioning this summary:
In OmniOS the steps are:
- install gcc compiler (it's one of the available packages) and put it in the PATH;
- install gnu-make (it's another package);
- export PATH=/usr/gnu/bin:/opt/gcc-4.8.1/bin/gcc:$PATH to give gmake higher priority over normal make (the assignment "?=" works only on gmake and I would suggest its removal unless really needed);
- compile and install LUA:
- modify Makefile to specify:
  CC = gcc
  MYLIBS = -lsocket
  LIBDIRS = -L/usr/local/lib
- run compilation

I would suggest to prepare a Makefile.OmniOS already with these changes. In case you need it, this is uname -a:
SunOS OmniOS-Xeon 5.11 omnios-f090f73 i86pc i386 i86pc
