### ISSUE TITLE
linenoise - better repl

### ISSUE THREAD

**Issue by Laeeth** [lefcha/imapfilter#113]
Hi.

I made a version of the imapfilter repl that uses the linenoise terminal library rather than plain fgets.  It's appealing to be able to flip through the history and edit the commandline using cursor keys (which don't work for me running Arch Linux).

Let me know if this might be interesting and I will tidy up into a pull request.

The one thing missing is to be able to copy and paste code from an editor into the console - I guess you have to use dofile instead.

I also have a sublime REPL config that allows you to run imapfilter that way.

Np if not interesting (depends on licenses etc) but let me know if so.

Laeeth.

**Comment by lefcha** [comment]
This is quite interesting, I didn't know about linenoise, and I will look into it, when I have some time. Thanks!

**Comment by Laeeth** [comment]
Let me know if you would like me to tidy up into a pull request.  Laeeth.

**Comment by lefcha** [comment]
I finally got the time to look into this, and [antirez/linenoise](https://github.com/antirez/linenoise) is indeed very nice and also simple to integrate, but unfortunately distributions (eg. Debian) don't include it yet, and I don't want to include such a large file inside of the imapfilter distribution.

Also there's seem to be a Lua module [hoelzro/lua-linenoise](https://github.com/hoelzro/lua-linenoise) that wraps linenoise, and by dynamically including in imapfilter's config file, it's very easy to startup a Lua prompt like this (this bypasses imapfilter's `-i` interactive mode):

```lua
linenoise = require('linenoise')
function prompt()
    while (true) do
        line = linenoise.linenoise(">> ")
        if line == nil then break end
        load(line)()
        linenoise.historyadd(line)
    end
end

prompt()
```

So I'm closing this for now...
