### ISSUE TITLE
Help writing rules

### ISSUE THREAD

**Issue by hanshafner** [lefcha/imapfilter#119]
Hi there,

thank you for this great utility that seems to just work!

I would like to filter messages based on a whitelist that I create myself. Code below. The whitelist will eventually have around 2000 addresses (the previous recipient list from Mail.app).

My question: the way I'm doing it now I think I will make 2000 (well, the number of addresses in the addressesFiltered list) connections each time I run imapfilter. I understand that that's not a good thing.

What I haven't managed so far is to get all the messages from the server into a table that I can then compare to my other table.

In other words: what exactly is the output of account1.INBOX:is_unseen() so that I can work with it as a table?

Thank you and kind regards.

`local addressesFiltered = { "address1@example.com", "address2@example.com", "address3@example.com" }

-- temporarily move whitelist messages to "Wanted"
for i,currentAddress in ipairs(addressesFiltered) do
	WantedMessages = account1.INBOX:is_unseen() *
			  account1.INBOX:contain_from(currentAddress)
			  WantedMessages:move_messages(account1["Wanted"])
end

-- move the rest of the messages to "Unwanted"
UnwantedMessages = account1.INBOX:is_unseen()
UnwantedMessages:move_messages(account1["Unwanted"])

-- move "Wanted" messages mack to inbox
WantedMessages2 = account1.Wanted:is_unseen()
WantedMessages2:move_messages(account1["INBOX"])`

**Comment by hanshafner** [comment]
Hello again,

I found a solution (link below) that worked for me, even though I don't really understand how Lua goes through the instructions. But that has to do with me not really understanding object oriented programming. I hope I will at some point.

http://www.npcglib.org/~stathis/blog/2012/07/09/linux-task-sorting-mail-with-imapfilter/

Kind regards
Hans

**Comment by lefcha** [comment]
The thing is that all the searching functions, like `is_unseen()`, do not return the actual messages, but only a number, the so called UID, which is a unique identifier that distinguishes each message.  So it doesn't help if you want to filter all unseen messages based on the `From` header field.

The way you are filtering on your example is one way of working and is the simplest, ie. you search for any unseen messages that have that specific `From` header field.  This makes sense if you have thousands or maybe hundreds of new messages each time you filter.

But if you have few new messages, and considering you have almost 2000 filters, it might make more sense to fetch the `From` header field of each unseen message, then check it locally, and decide whether to keep the message on `INBOX` or move it elsewhere.  This would look something like this:

```lua
unseen = account1.INBOX:is_unseen()
results = Set {}
for _, mesg in ipairs(unseen) do
    mbox, uid = table.unpack(mesg)
    from = mbox[uid]:fetch_field('From')
    approved = false
    for _, addr in ipairs(addresses) do
        if from:find(addr) then
            approved = true
            break
        end
    end
    if not approved then
        table.insert(results, mesg)
    end
end
results:move_messages(account1.unwanted)
```

For more examples on doing similar things, by using imapfilter's methods and some Lua code, have a look at the [extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua) file.
