### ISSUE TITLE
Get stdout from pipe_to + add fields to e-mails

### ISSUE THREAD

**Issue by odins-raven** [lefcha/imapfilter#12]
I have another issue that I could not solve. I want imapfilter to pipe messages to SpamProbe, which then produces a string indicating whether the message is spam or not. Such a string looks something like
`SPAM 0.9999491 5f38371130717de32108b70ac623fd34`.
It is sent to **stdout**.

Based on the sample file, I wrote the following for imapfilter:

```all = GMAIL.INBOX:select_all()
spammsgs = Set {}
for _, msg in ipairs(all) do
    mbox, uid = unpack(msg)
    msgtxt = mbox[uid]:fetch_message()
    result = pipe_to('/sw/bin/spamprobe train', msgtxt)
    print(result)
    if (string.sub(result,1,4) == "SPAM") then
        table.insert(spammsgs, msg)
    end
end
spammsgs:move_messages(GMAIL.SPAM)

``````

The problem is that pipe_to() returns the return value of SpamProbe (which always is 0 if no error occurred) instead of stdout. How can I capture stdout instead?

A second question: Is there a way to add fields to a e-mail? In fact, I'd like to add something like
```X-SpamProbe: SPAM 0.9999491 5f38371130717de32108b70ac623fd34```
to the message header itself. With this information I could check whether a message has been checked, apply further filters in my e-mail client, read the spam level, etc.

I guess this is a rather general question: How can I replace (i.e., append) a message on the IMAP server via imapfilter that imapfilter fetched and some external tools (via pipe) modified?

Again, any help is highly appreciated.
``````

**Comment by drzraf** [comment]
Why is there such a limitation? Technically one should be able to bind stdin of a subprocess and then grab both return code and output isn't?
