### ISSUE TITLE
fetch_message loop timeout

### ISSUE THREAD

**Issue by mathroc** [lefcha/imapfilter#121]
on some messages, `mbox[uid]:fetch_message()` goes into an infinite loop :

```
C (3): 102A UID FETCH 7795 BODY.PEEK[TEXT]
imapfilter: timeout period expired while waiting to read data
S (3): * OK [KAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready. (stunnel)
C (3): 102B CAPABILITY
S (3): 102B OK Pre-login capabilities listed, post-login capabilities have more.
C (3): 102C STARTTLS
S (3): 102C OK Begin TLS negotiation now
C (3): 102D CAPABILITY
S (3): 102D OK Pre-login capabilities listed, post-login capabilities have more.
C (3): 102E LOGIN "mathieu@texthtml.net" *
S (3): 102E OK Logged in
C (3): 102F CAPABILITY
S (3): 102F OK Capability completed.
C (3): 1030 NAMESPACE
S (3): 1030 OK Namespace completed.
C (3): 1031 SELECT "Junk"
S (3): 1031 OK [READ-WRITE] Select completed (0.000 + 0.000 secs).
C (3): 1032 UID FETCH 7795 BODY.PEEK[TEXT]
imapfilter: timeout period expired while waiting to read data
S (3): * OK [KAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready. (stunnel)
C (3): 1033 CAPABILITY
S (3): 1033 OK Pre-login capabilities listed, post-login capabilities have more.
C (3): 1034 STARTTLS
S (3): 1034 OK Begin TLS negotiation now
C (3): 1035 CAPABILITY
S (3): 1035 OK Pre-login capabilities listed, post-login capabilities have more.
C (3): 1036 LOGIN "mathieu@texthtml.net" *
S (3): 1036 OK Logged in
C (3): 1037 CAPABILITY
S (3): 1037 OK Capability completed.
C (3): 1038 NAMESPACE
S (3): 1038 OK Namespace completed.
C (3): 1039 SELECT "Junk"
S (3): 1039 OK [READ-WRITE] Select completed (0.000 + 0.000 secs).
C (3): 103A UID FETCH 7795 BODY.PEEK[TEXT]
```

and it keeps going on and on, trying to "UID FETCH 7795 BODY.PEEK[TEXT"

I don't exactly understand what is going here because I can look at the message without issue in different mail client and I don't have errors on the imap server logs. Once I delete the offending message, imapfilter happily works with the other messages.

This issue seems to appear with message containing chinese characters. My guess is that there is a difference between the length of the message body (I suppose the imap server tells imapfilter the body length and then send the body) and the length of the message body received calculated by imapfilter. and that imapfilter keeps waiting for the end of the body and timeout.

note: only the body fails, getting the headers works

**Comment by lefcha** [comment]
I think you're right in your assumption of what the problem is.  And the reason why it goes into a loop is the recover mechanism tries to reconnect and continue from where it failed, when some error takes place (mostly network errors).

Can

**Comment by lefcha** [comment]
I think you're right in your assumption of what the problem is.  And the reason why it goes into a loop is the recover mechanism tries to reconnect and continue from where it failed, when some error takes place (mostly network errors).

Does this problem happens all the time when there are Chinese characters?  Could you maybe try to reproduce this problem with a short message with such characters, or send me in private some specific message body that causes this error? Thanks!

I will try myself to reproduce it with some Chinese characters, but I'm not sure if I will succeed...

**Comment by mathroc** [comment]
it's not really easy, if I copy & paste the same content into a new email, I don't have the problem, same if I forward it.

maybe it's related to its headers?? the original mail have `Content-Type: text/plain;charset="GB2312"`. while the cop&pasted one have `Content-Type: text/plain; charset=utf-8` and the forwarded one have :
```
Content-Type: multipart/alternative;
 boundary="------------080406050104020308060200"

This is a multi-part message in MIME format.
--------------080406050104020308060200
Content-Type: text/plain; charset=gbk; format=flowed
Content-Transfer-Encoding: 8bit
```

I'll try to dig into .Maildir to find the mail file and attach it here

**Comment by lefcha** [comment]
I see.  If you can find anything that will help debug this it would be very helpful. Thanks in advance.

**Comment by mathroc** [comment]
[This mail](https://github.com/lefcha/imapfilter/files/191127/mail.txt) (from .Maildir folder on the server) causes imapfilter to hang on 

> UID FETCH 7954 BODY.PEEK[TEXT]

I'm sorry, every mail that causes this problems seems to be rather large. I hope it can be helpful

**Comment by lefcha** [comment]
I appended using Mutt a new message on my local Dovecot IMAP server, with exactly the same content as the message you sent me (thanks a lot), and I checked the resulting message on my Maildir `cur` directory, and it seems to be 7039 bytes, that is exactly the same as the file you sent me, and also `cmp` reports them as identical.

But imapfilter seems to be able to do a `fetch_body()` on that email just fine, so I could not reproduce this problem this way.

Can you run imapfilter with `-d imapfilter.log` just trying to do a `fetch_body()` on that message, then have a look at the `imapfilter.log` file and report back to me any strange findings in the `FETCH` command's response, and also the message length you get back, which can be found in a line like this:

`* 7 FETCH (UID 7954 BODY[TEXT] {6203}`

In the above example the body length is reported to be 6203 bytes, and it is for the message you sent me...
