### ISSUE TITLE
any (best) way to use gmail imap extensions ?

### ISSUE THREAD

**Issue by maxandersen** [lefcha/imapfilter#124]
especially X-GM-RAW on searches would be interesting (see https://developers.google.com/gmail/imap_extensions#extension_of_the_search_command_x-gm-raw).

**Comment by lefcha** [comment]
At the moment there are no plans to support any more IMAP extensions, unless there are some that are widely used and very useful.  But supporting extensions that are haven't become an RFC, that are only used by a single vendor, and that may change often, is unfortunately quite unlikely.

But specifically for this kind of searches, actually imapfilter already can be used to send them using the `send_query()` method, like this:

```lua
gmail.INBOX:send_query('X-GM-RAW "has:attachment in:unread"')
```

I have actually tried that myself and it seems to work fine with the `UID SEARCH` that imapfilter is sending, and the actual messages (UIDs) are returned as expected.  So please give that a try yourself...

**Comment by maxandersen** [comment]
fwiw that actually worked for me thus that is awesome :)
