### ISSUE TITLE
Can't connect to iCloud

### ISSUE THREAD

**Issue by damienweiss** [lefcha/imapfilter#125]
When I try to connect to my iCloud account, I get a Authentication failed error:

S (3): * OK [CAPABILITY st11p00mm-iscream022 15E205 XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] iSCREAM ready to rumble (15E205-0982aaf890fd:18514) st11p00mm-iscream022 [04:19:14:31:21:53]
C (3): 1000 CAPABILITY
S (3): 1000 OK !!
C (3): 1001 LOGIN "damien" *
S (3): 1001 NO [AUTHENTICATIONFAILED] Authentication failed
imapfilter: IMAP (3): 1001 NO [AUTHENTICATIONFAILED] Authentication failed
C (3): 1002 CAPABILITY
imapfilter: reading data through SSL; EOF in violation of the protocol
imapfilter: login request to damien@imap.mail.me.com failed
stack traceback:
	[C]: in function 'error'
	/usr/share/imapfilter/account.lua:68: in function '_check_result'
	/usr/share/imapfilter/account.lua:84: in function '_login_user'
	/usr/share/imapfilter/account.lua:46: in function 'IMAP'
	/home/dw/.imapfilter/config.lua:7: in main chunk

My config.lua is pretty simple to try to troubleshoot what's going on:

options.timeout = 120
options.create = true
options.subscribe = true
options.expunge = true
options.starttls = false

icloud = IMAP {
	server = 'imap.mail.me.com',
	username = 'damien',
	password = 'mypassword',
	ssl = 'ssl2',
	
}

icloud.INBOX:check_status()

I've tried many iterations of my username, (damien@mac.com, damien@icloud.com, etc).  I've made sure that I can log in via a web browser and a mail client (I can).  No matter what I do, I get the same error.

**Comment by lefcha** [comment]
Well the problem here seems to be a wrong username or password, and you should use the same username and password as you use on other mail clients.  But also try to not use `ssl2` but another version of the SSL protocol, such as `tls1.2`, `tls1.1` or `tls1`.

**Comment by damienweiss** [comment]
So I figured this one out.  It turns out that it *was* the wrong password.  Apple requires you to get an app specific password for non-Apple clients.  Did that, and this was all cleared up.
