### ISSUE TITLE
imapfilter: initiating SSL connection to imap.gmail.com; error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by maxandersen** [lefcha/imapfilter#129]
Recently imapfilter started to give me this error:
```
imapfilter: initiating SSL connection to imap.gmail.com; error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
```

tried rebuilding from source but no luck yet.

**Comment by lefcha** [comment]
Have you tried using one of the TLS protocols by setting the account's `ssl` option to `tls1`, `tls1.1` or `tls1.2`? The older `ssl3` protocol is now being deprecated and disabled by many servers and client libraries...

**Comment by maxandersen** [comment]
That did the trick! have had that setting for years so didn't even consider that being what changed. Thanks!

**Comment by Papafox** [comment]
Google has dropped support for SSLv3 and TLS1.0.  I'm not sure about TLSv1.1, it may be supported.  The only protocol guaranteed to work is TLSv1.2

**Comment by hferentschik** [comment]
You guys saved my day. Had exactly the same issue.

> That did the trick! 

+1

> have had that setting for years so didn't even consider that being what changed.

Same here :-)

**Comment by mellowcandle** [comment]
Thanks, helped me also !
