### ISSUE TITLE
How to filter filtered messages

### ISSUE THREAD

**Issue by tomaso** [lefcha/imapfilter#130]
Hi,

this is not really an issue, but a request for suggestion on how to use imapfilter more efficiently.
I have several filters using logical operators to get fine filtering, but I would like to remove emails that were already filtered from the further filtering.

Example: I want to filter emails with subject like "alarm" but not if they are from a particular "sender".
I can implement this with account:contain_subject("alarm")-account:contain_to("sender")
But since this "sender" is special in other rules too I need to put this '-account:contain_to("sender")' everywhere.

I would prefer to remove it from the results at the beginning and only filter the results in the latter rules.

I tried with the following, but it does not work:

m = account['INBOX']:is_unseen()
messages = m * account['INBOX']:contain_subject("subject1")
messages:move_messages(account['folder'])
m = m - messages

The last line is not correct lua because of typing. 

Thank you for any help.

**Comment by lefcha** [comment]
You could first store the messages originating from that sender, and reuse it like this:

```lua
sender = account.INBOX:contain_to('sender')
subject1 = account.INBOX:contain_subject('subject1') - sender
alarm = account.INBOX:contain_subject('alarm') - sender
...
```

Or you could store messages not originating from that sender, and then do meta-searching like this:

```lua
not_sender = account.INBOX:select_all() - account.INBOX:contain_to('sender')
subject1 = not_sender:account.INBOX:contain_subject('subject1')
alarm = not_sender:account.INBOX:contain_subject('alarm')
```
