### ISSUE TITLE
Delete Gmail Trash Chromebook

### ISSUE THREAD

**Issue by kmages** [lefcha/imapfilter#134]
How could I run something like this on a Chromebook as an extension or app?  I want to empty my Gmail trash more frequently than 30 days.  Every minute or hour would be ideal.  Thanks!!

**Comment by kmages** [comment]
Here is a Google Script that claims to work, but does not.

Create the following function in my script:
function deleteForever(userId, labelName) {
  var threads = GmailApp.search("in:trash label:" + labelName);
  for (var i = 0; i < threads.length; i++) {
    Gmail.Users.Messages.remove(userId, threads[i].getId());
  }
}
To enable advanced services for this script, locate Resources on the menu, and select Advanced Google services...
Enable Gmail API on the list.
Before selecting OK, click on the Google Developers Console link. Search for gmail, and enable the service there as well.
Done, select OK; the function should now work. (Comment: as mentioned in the link @karan provided, one can use "me" for userID, or alternatively provide one's Gmail address: "<address>@gmail.com".)
(Steps to enable advanced services for my script are based on Google's guide [here](https://developers.google.com/apps-script/guides/services/advanced#enabling_advanced_services.)

**Comment by lefcha** [comment]
Well, you can make imapfilter delete your thrash as often as you want if that's what you want to know.
