### ISSUE TITLE
Calling status in the selected mailbox is undefined behavior

### ISSUE THREAD

**Issue by DelusionalLogic** [lefcha/imapfilter#136]
According to the IMAP REV1 spec, [RFC 3501](https://tools.ietf.org/html/rfc3501#page-44), invoking select on the currently selected mailbox is undefined, and therefore isn't guaranteed to actually update.

In office 365, just as an example, a status on the selected mailbox always returns the same result as the original select. That means you can't rely on the `UIDNEXT` to change when a new message arrives.

An easy workaround is to place a `account.<mailbox>:_cached_select()` to some other mailbox before all `check_status()` calls. It's not ideal, since it relies on implementation details (any method starting with _ is considered private).

The correct fix would be to use the `EXAMINE` command when trying to get the status of the currently selected mailbox.

**Comment by lefcha** [comment]
I think what we can do in this case is when the user wants to know the `STATUS` of the currently selected mailbox, we `CLOSE` it first.  If the user wants to know the `STATUS` of a mailbox that is not selected, we don't change anything.

**Comment by lefcha** [comment]
Closed by 9e95c1dda460de7b1c7d02063dd875b700e6222f.
