### ISSUE TITLE
Running on Android?

### ISSUE THREAD

**Issue by kkaczmarczyk** [lefcha/imapfilter#137]
Hi, Could you think of easiest way of installing and running imapfilter on Android device? I am not an expert, but was able to install it using Termux app. It required some effort though and I am curious whether it could be easier, more seamless. Any tries before?

**Comment by lefcha** [comment]
Unfortunately, I haven't ever tried to build or run imapfilter on Android before, and I don't have any experience on Android to give it a quick try.  Maybe someone else has done this?

**Comment by kkaczmarczyk** [comment]
FWIW I installed it in the Termux app, which is Linux environment emulator for Android. It wasn't seamless but worked in the end (required installation of many apt packages manually and linking C libraries to install Lua). Probably there are better ways to achieve it.
