### ISSUE TITLE
Spam filtering?

### ISSUE THREAD

**Issue by damienweiss** [lefcha/imapfilter#138]
While I've found some people online that have claimed success, these blog entries are old or they integrate other ideas (gnu keyring for instance) that seem to be too much in a way that is difficult to separate out.

So does anyone know of a way to integrate a good Bayesian spam filter with imapfilter?

**Comment by lefcha** [comment]
Does [this example](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua#L23-L44) come close to what you want?
