### ISSUE TITLE
Strange quoting cause false negative

### ISSUE THREAD

**Issue by mmcco** [lefcha/imapfilter#139]
I recently received an email with the following CC:

```
"OpenBSD misc"" <misc@openbsd.org>
```

This should have matched the pattern `contain_cc('misc@openbsd.org')`, but it didn't. I expect that the extra quote after the real name section interfered. Is this a bug, or are the participating MTA's simply accepting an invalid address format?

Thanks for your time,
Mike

**Comment by lefcha** [comment]
The `contain_cc()` function just sends a `SEARCH` query to the server to search for messages that contain the specified string in the `Cc` header field, so if there's a bug it should be in the server's implementation of the `SEARCH` function.

Just to verify that the server is not sending back any error, you can enable `-d debug.log` and have a look inside it to see what the server replies on your search request.  If it just sends back an empty reply, which means no messages matched, then it's a problem in its `SEARCH` implementation.

In that case, you can either contact the server's software developers and report the problem, or you can work around this by using imapfilter's `match_cc()` function, which downloads the `Cc` header field of all messages in the mailbox, and does the matching locally (it also accepts Perl-like regular expressions).
