### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unsupported protocol vs Office365

### ISSUE THREAD

**Issue by lxsli** [lefcha/imapfilter#140]
Version 1:2.6.4-1:

  IMAPFilter 2.6.4  Copyright (c) 2001-2015 Eleftherios Chatzimparmpas

Output:

  imapfilter: initiating SSL connection to outlook.office365.com; error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
  imapfilter: login request to alexisl@hpe.com@outlook.office365.com failed
  stack traceback:
  	[C]: in ?
  	[C]: in function 'error'
  	/usr/share/imapfilter/account.lua:81: in function '_check_result'
  	/usr/share/imapfilter/account.lua:97: in function '_login_user'
  	/usr/share/imapfilter/account.lua:59: in function 'IMAP'
  	/home/lealexis/.imapfilter/config.lua:15: in main chunk

I've tried to compile imapfilter myself but the result coredumps. I might have some squiffy libs due to dist-upgrading.

**Comment by lxsli** [comment]
Oh and I ran with "-d debug.log" but the file was empty.

**Comment by Papafox** [comment]
The unsupported protocol error usually indicates that connection using an
old protocol (prior to TLS1.1) is being attempted.

Try specifying "ssl = 'tls12'"


Matthew






————————————————————————————————————————————————————
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by lxsli** [comment]
Amazing, thank you! I feel dumb, totally forgot ssl = 'ssl23' was in my config.
