### ISSUE TITLE
document how to delete_messages by uid

### ISSUE THREAD

**Issue by drzraf** [lefcha/imapfilter#147]
see http://lists.hellug.gr/pipermail/imapfilter-devel/2011/000839.html
`delete_messages` appears to apply on a result set only.
But here and there we can find sample setting a result set as a parameter.
Anyway I can't find a way to delete a message, given its uid, in the context of iterating over a result-set.

**Comment by lefcha** [comment]
There are some examples on creating sets and adding items to them, and finally applying an action to the messages that they contain in the [samples/extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua) file.

You basically create an empty set with something like `messages = Set{}`, and then for each message you want to process you append, to your newly created set, a table with two elements: the mailbox and the UID of the message.  For example, if you have a message with UID `123` which belongs to the mailbox `myaccount.INBOX`, then you just do `table.insert(messages, {myaccount.INBOX, 123})`.

This set is exactly the same as a the results from some search function, so you can then call any processing function you want on it.  Note, that you can apply the same action to messages in different mailboxes even in different accounts, as imapfilter can figure out where each message belongs to, in addition to knowing its UID.
