### ISSUE TITLE
Cert verification exception handling

### ISSUE THREAD

**Issue by internationils** [lefcha/imapfilter#148]
Hello,
I'm getting a failed certificate (expected... it's an expired LE cert where I still need to move the new one over from my webserver...). It would be nice if 
- imapfilter would catch the exception and fail gracefully
- report why the certificate verification failed (as opposed to a stacktrace)

Thanks
Nils
```
imapfilter: certificate verification failed; 10
imapfilter: login request to nils@localhost failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/usr/local/share/imapfilter/account.lua:81: in function '_check_result'
	/usr/local/share/imapfilter/account.lua:97: in function '_login_user'
	/usr/local/share/imapfilter/account.lua:59: in function 'IMAP'
	/home/nils/.imapfilter/config.lua:33: in main chunk
```

**Comment by lefcha** [comment]
Good point.

Can you try the latest version from git, commit  b1e4cf3d5b7e0abd68419fbd9cb9c8e0abda96ec should fix this.

**Comment by internationils** [comment]
Thanks... cert is up to date now though :) Else you can generate a staging cert with LE to test, and that should fail as a selfsigned cert...

**Comment by lefcha** [comment]
:+1:
