### ISSUE TITLE
Exception handling for connection issues

### ISSUE THREAD

**Issue by internationils** [lefcha/imapfilter#149]
I have two more errors resulting in exceptions... the first is an incorrect account, the second is a connection reset (possibly dovecot updating and hence not responding). Both should result in errors, not in exceptions if at all possible.
Thanks!

Thu Jan  5 14:40:00 2017: error while initiating connection to somewhereelse.org at port 993
Thu Jan  5 14:40:00 2017: login request to username@somewhereelse.org failed
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        /usr/local/share/imapfilter/account.lua:81: in function '_check_result'
        /usr/local/share/imapfilter/account.lua:97: in function '_login_user'
        /usr/local/share/imapfilter/account.lua:59: in function 'IMAP'
        /home/nils/.imapfilter/config.lua:42: in main chunk

Thu Jan  5 20:22:40 2017: initiating SSL connection to localhost; Connection reset by peer
Thu Jan  5 20:22:40 2017: idle request to myuser@localhost failed
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        /usr/local/share/imapfilter/mailbox.lua:46: in function '_check_result'
        /usr/local/share/imapfilter/mailbox.lua:1069: in function 'enter_idle'
        /home/nils/.imapfilter/config.lua:492: in main chunk

**Comment by lefcha** [comment]
The problem with these cases is that imapfilter could not continue with the execution of the config, as there's probably no active session anymore (eg. connection to the server), so it probably makes no sense to process the rest of it.  This is the reason why I decided to produce an exception in such cases, as I think imapfilter should better abort, and imagine a scenario where a request to copy some messages failed, and then imapfilter tried to reconnect and continue with the next request which deletes those messages.

But there's been some suggestion some time ago, that maybe imapfilter's recovery mechanism (see `option.recover`) should be more persistent and keep trying to reconnect and execute the command that failed, in hope that it was a temporary problem (eg. network outage). And actually, I've come up with something like that, but I didn't commit it yet.  So let me check again that code, and maybe I can push it soon.
