### ISSUE TITLE
Graphical Interface

### ISSUE THREAD

**Issue by Pofilo** [lefcha/imapfilter#150]
Hey ! 

I'm really interested by this project but my only issue is to edit the configuration of filters in files in lua.
It's not really convenient when you have a little rule to add or something like that.

That's why I asked myself if someone has worked on a graphical interface for _imapfilter_. It could be very simple to use, you could add rules easily and it would generate the lua config file.

Is there already a project like that ?
Otherwise, I will try to do it by myself when I will have some time :)

**Comment by lefcha** [comment]
Hello!

Some people have asked about as GUI in the past, but mostly before imapfilter was using Lua to configure it, as its config was simpler, while now it's more or less limitless.

I think the basic functionality of writing rules could be provided by a GUI, although it would be more complicated to be able to parse/read config files, especially after they've been modified manually.

Anyhow, to come to your question, I'm not aware of any GUI available, and of course you're always welcome to try to come up with if you have the time :-)
