### ISSUE TITLE
[Feature] Remove Line Breaks

### ISSUE THREAD

**Issue by Jaydabi** [lefcha/imapfilter#151]
When using match_subject() with ^ and $ on long subjects it won't work since there are line breaks (\n) in the message source. It would be nice to have the ability to remove those, either as a hard-coded behavior of the named function or with a flag.

**Comment by lefcha** [comment]
You can actually use [internal option settings](http://pcre.org/original/doc/html/pcrepattern.html#SEC13) in your pattern, so try playing with the `m` (multiline) and/or `s` (dotall) modifiers.  You could enable them both by prepending `(?ms)` at the start of your pattern.
