### ISSUE TITLE
IDLE connection dies without recovery

### ISSUE THREAD

**Issue by m-ober** [lefcha/imapfilter#153]
I'm using a rather simple script:
```lua
options.subscribe = true
options.namespace = false
options.timeout = 60 -- seconds
options.recover = all 
options.reenter = true 
options.persist = true
options.wakeonany = false
options.keepalive = 1 -- minutes

function forever()
while true do
	unseen_messages = account2["INBOX"]:is_unseen() 
	
	-- .....

	print("*** Now idling: " .. os.date())
	account2["INBOX"]:enter_idle()
end
end

forever()
```

You can see that I set the keepalive time to a very short value of 1 minute. Any value larger than that and the connection seems to die silently and imapfilter does not seem to notice that. New mails are not filtered and imapfilter never sends another IDLE command. It just hangs/stalls forever.

I'm using the latest version, i.e. v2.6.10-5-g9e95c1d.

**Comment by lefcha** [comment]
I can see a possible cause in the above config as the line

```lua
options.recover = all
```

basically sets the `options.recover` to `nil`, as `all` is a variable name that is not defined.  This disables the recover mechanism, and thus `options.persist` isn't taken into account here.

The correct line is should set it to the `'all'` or `"all"` string like this:

```lua
options.recover = 'all'
```

**Comment by m-ober** [comment]
Thanks. This might be a solution to #154, which I'm testing right now.

Unfortunately, for the issue reported in this ticket, setting this option to `'all'` instead of `all` does not change anything. Setting `options.keepalive` to anything higher than `1` and the last message on the console I see is
```
C (3): 100F IDLE
```
Then, if some mail arrives, imapfilter is just doing nothing. Setting `options.keepalive = 1` and "refreshing" the connection every minute is working fine.

**Comment by lefcha** [comment]
The `timeout` option is used when reading data from the server, and it specifies how long should imapfilter wait for the server to return some data.  For example setting it to `60` means wait up to 60 seconds before considering the read operation as unsuccessful, and thus the connection as dead.

Now the `keepalive` is only used on the `IDLE` request, and it bypasses the `timeout` above, meaning that the `timeout` is ignored.  Instead `keepalive` controls how often to quit the `IDLE` mode and resend a new `IDLE` command.

If your server drops the connection for a `keepalive` more than 1 minute, then for sure it's problematic.  An IMAP server must allow the IDLE command to be running without activity (network traffic) for at least 30 minutes, so this means this server is not standards compliant.

If the server drops silently the connection after 1 minute, then I suggest that you don't use IDLE at all, as it doesn't make any sense.  The purpose of the IDLE mode is to not poll the server very often eg. every minute, every 5 minutes, etc.  If you need to exit IDLE and reenter every minute, this is clearly problematic.

As the server is not cooperating according to the IMAP RFCs, I instead recommend to just do the filtering inside a loop, and then sleep for like 1 or more minutes (try to see whatever works without the server dropping the connection.  If the server still drops the connection very often, I suggest you close the connection, and reopen it every few minutes.

You can logout from the server at the end of the loop like this:

```lua
options.timeout = 60
[...]

while true do
    myserver = IMAP {
        server = 'mail@example.com'
        username = 'me',
        password = 'secret'
    }
    [...]
    myserver:logout()
    sleep(5)
end
```
