### ISSUE TITLE
Scripts broken by upgrade to imapfilter 2.6.10

### ISSUE THREAD

**Issue by numist** [lefcha/imapfilter#155]
Can't remember what version I was running before, but the error is:

```
imapfilter: ...al/Cellar/imapfilter/2.6.10/share/imapfilter/mailbox.lua:153: attempt to compare number with nil
stack traceback:
	[C]: in function '__lt'
	...al/Cellar/imapfilter/2.6.10/share/imapfilter/mailbox.lua:153: in function '_flag_messages'
	...al/Cellar/imapfilter/2.6.10/share/imapfilter/mailbox.lua:694: in function 'delete_messages'
	.../local/Cellar/imapfilter/2.6.10/share/imapfilter/set.lua:210: in function 'delete_messages'
	dedupe.lua:5: in function 'delete_duplicates'
	dedupe.lua:22: in function 'mailbox_dedup'
	dedupe.lua:34: in function 'f'
	header.lua:269: in function 'mailbox_foreach'
	dedupe.lua:36: in main chunk
```

And can be worked around by adding `options.limit = 0` to the script prologue.

The code producing the error in `mailbox.lua` is:

```
    if options.limit > 0 then l = options.limit end
```

It would be nice if it applied a default value when one isn't already provided instead of crashing.

**Comment by lefcha** [comment]
Well the `options.lua` file which is loaded during imapfilter startup actually initializes these kind of variables and it sets `options.limit = 0`, so possibly this could happen if one overwrites the `options` variable with a new table, instead of modifying the original table created by imapfilter.  Do you do something like that in your case?

**Comment by lefcha** [comment]
Also, what was the last version that didn't have this problem? Because nothing related changed between 2.6.9 and 2.6.10, that could cause such an error...

**Comment by numist** [comment]
Ahh yes, I am indeed overwriting the options variable instead of modifying it. Thanks! Ok to close.

I was running a fairly old version of imapfilter, it had been at least a year since the last update.
