### ISSUE TITLE
Add header to message?

### ISSUE THREAD

**Issue by spiffytech** [lefcha/imapfilter#156]
Is it possible to add a header to a message? (I want to [enable conversation threading](https://people.dsv.su.se/~jpalme/ietf/message-threading.html) for JIRA notices).

**Comment by lefcha** [comment]
Yes and no, that is you can't directly edit a message this way as IMAP doesn't support it, but you could fetch a whole message with `fetch_message()`, insert the new header in the right place, upload the modified message with `append_message()` to the server, and then delete the original with `delete_messages()`.

Also, I suppose you could create a helped function that takes the message UID and the header to add, and perform all these actions, and you would end up having a function that appends a header to a message.

**Comment by spiffytech** [comment]
What's the best way to set the new header on a Lua message object?

**Comment by lefcha** [comment]
I suppose you could just insert the header in the beginning of the message string, as the order of the header fields doesn't matter.  So something like:

```lua
message = myaccount:mymailbox[uid]:fetch_message()
message = 'X-My-Header: foo\r\n' .. message
```

Eitherwise, you could use Lua's `gsub()` to insert it somewhere else, eg. after some specific header field, etc.
