### ISSUE TITLE
question: is there a way to translate Thunderbird filters to imapfilter?

### ISSUE THREAD

**Issue by monperrus** [lefcha/imapfilter#157]
Hi,

I extensively use Thunderbird filters.

Is there a way to automatically translate Thunderbird filters to imapfilter?

**Comment by lefcha** [comment]
I'm not aware of such of tool, and if you didn't find anything by searching the web, it probably doesn't exist.  It should be possible and not very difficult for someone to write one though...

**Comment by monperrus** [comment]
Thanks
