### ISSUE TITLE
question: Is there a way to find the encoding of an attachment?

### ISSUE THREAD

**Issue by merlinblack** [lefcha/imapfilter#158]
Hi,

I'm using imapfilter to grab CSV files sent to an email account and save them along with some info on the sender etc for another program to process. I have it working perfectly if the email is sent from outlook as the CSV gets base64 encoded, which I decode as part of the saving process.

Unfortunately, not all email clients will always base64 encode a CSV file. My personal webmail, just adds it as plain text.

Is there way to check the encoding of an attachment in addition to its 'type'?  I could not find anything by printing out the respective tables.

I've also tried a brute force method, just trying to decode and then just outputting if 'base64' returns non-zero. This almost works, except that occasionally base64 'successfully' decodes plain text.

Thanks!

**Comment by lefcha** [comment]
Can you check the header of the emails, and try to find out what the `Content-Type` says on each type of CSV (plain and base64)?  Is there any difference that can differentiate the two?

**Comment by merlinblack** [comment]
Unfortunately the only 'Content-Type' in the headers is for the whole email - multipart/mixed.
I'm pretty sure there is a 'Encoding' header on the attachment/message part itself. I'm hoping to get at that, otherwise I'll have to write something in PHP or something instead of using imapfilter, which would be a shame - I like Lua. :-)

Perhaps I can grab the entire message and get it that way.

**Comment by merlinblack** [comment]
I've found a solution. It's a bit hacky but it gets the job done.

I'm grabbing the entire message, and using regex to first split the message into it's parts, then for each part find the info I need. The boundary regex was difficult, as emails from outlook have an extra newline in the middle compared to my Linux based webmail.  regex101.com came to the rescue there. Great site for figuring out regex.

It needs Lrexlua which can be obtained via luarocks, or your package management system.

Here's some code, albeit not super polished:

    function getMorePartInfo( message )
    local rex = require 'rex_pcre'

    -- See https://regex101.com/r/SFx55Y/2 for how the next regex works.

    local bdry_re = rex.new([[Content-Type:[\S\s]*?boundary="(.*)"]] )
    local type_re = rex.new([[Content-Type: ([\w/]*)]])
    local enc_re = rex.new([[Content-Transfer-Encoding: (\w*)]])

    local s, _, boundary = bdry_re:find( message )

    if s == nil then print( 'No boundary found' ) return {} end

    local partinfo = {}
    -- Skip the first two - so the indexes line up with the partid 
    -- from 'fetch_structure'
    local skip = 2
    for part in rex.split(message, boundary) do
        if skip > 0 then
            skip = skip - 1
        else
            local info = { type = '', encoding = '' }
            s,e,match = type_re:tfind(part)
            if s then info.type=match[1] end
            s,e,match = enc_re:tfind(part)
            if s then info.encoding=match[1] end
            table.insert( partinfo, info )
        end
    end
    return partinfo
    end

This returns a table with the same indexing as the table returned by fetch_structure. Inside you have 'type' and 'encoding'.  You could add more.

The encodings I've seen so far are '8bit', 'quoted', and 'base64'.

I just pipe_to( 'cat ..... for 8bit, and pipe_to('base64 -d ...... for base64.  Only the message text seems to come as 'quoted'.
