### ISSUE TITLE
Is there a way to do an exact match without using regex?

### ISSUE THREAD

**Issue by ScriptJunky** [lefcha/imapfilter#159]
Here's an example --

My company has some employees that have e-mail addresses with only 3 characters.
The problem is those 3 characters are matched in other email addresses within the company. 

To work around this i have tried the following;

```lua 
dofile(os.getenv("HOME") .. "/.imapfilter/creds.lua")

print("Processing ppl.lua")

sender = account1["INBOX"]:contain_from("bid@domain.com") *
         account1["INBOX"]:match_from("^bid@domain.com$")
sender:move_messages(account1["domain/[USERS]/Bidnar Petticoat"])

print("\n")
```

```lua 
dofile(os.getenv("HOME") .. "/.imapfilter/creds.lua")

print("Processing ppl.lua")

sender = account1["INBOX"]:match_from("^bid@domain.com$")
sender:move_messages(account1["domain/[USERS]/Bidnar Petticoat"])

print("\n")
```

```lua 
dofile(os.getenv("HOME") .. "/.imapfilter/creds.lua")

print("Processing ppl.lua")

sender = account1["INBOX"]:contain_from("bid@domain.com") *
         account1["INBOX"]:match_from("\bbid@domain.com\b")
sender:move_messages(account1["domain/[USERS]/Bidnar Petticoat"])

print("\n")
```

```lua 
dofile(os.getenv("HOME") .. "/.imapfilter/creds.lua")

print("Processing ppl.lua")

sender = account1["INBOX"]:contain_from("bid@domain.com") *
         sender:match_from("^bid@domain.com$")
sender:move_messages(account1["domain/[USERS]/Bidnar Petticoat"])

print("\n")
```

All 4 queries end up with the same result where e-mails from that user are not moved to the dedicated folder. Am I doing something wrong in my query structure? More than happy to accept problem is on my end.

That said, if it doesn't exist now, could **is_** be expanded in imapfilter?

* is_from
* is_to
* is_cc
etc....etc....?

**Comment by lefcha** [comment]
The `contain_from()` method is using the IMAP protocol's SEARCH query, which doesn't support metacharacters such as `^` or `$`, and so the only option in this case is to use `match_from()` which downloads the `From` header and does the matching locally using regular expressions (PCRE).

In this case as the `From` address could be in a format like `Name Surname <user@example.com` or `user@example.com` or `<user@example.com>, you could probably try to match all formats using `\b` (don't forget to use `\\b` inside the Lua string), so try:

```lua
sender = account1["INBOX"]:match_from("(?i)\\buser@example.com\\b")
```

**Comment by ScriptJunky** [comment]
Thanks, that worked great, albeit incredibly slow. I am currently structuring the query like so;

sender = account1["INBOX"]:contain_from("bid@domain.com") *
         account1["INBOX"]:match_from("(?i)\\bbid@domain.com\\b")
         sender:move_messages(account1["[GROUPS]/bid"])

My thought was that, by grabbing all items that contain_from bid@ first, it would take less time to regex match. It actually is working in that way, but is still incredibly slow (upwards of 2-5m every time, even in office).

**Comment by lefcha** [comment]
Try with meta-searching:

```lua
sender = account1["INBOX"]:contain_from("bid@domain.com"):match_from("(?i)\\bbid@domain.com\\b")
sender:move_messages(account1["[GROUPS]/bid"])
```

**Comment by ScriptJunky** [comment]
Structured that way it is much faster, thank you!

**Comment by lefcha** [comment]
Just out of curiosity, how much faster?

**Comment by ScriptJunky** [comment]
I knew you were going to ask that, so I had already planned to move some messages back to INBOX, and run some `time imapfilter -c <filter.lua>` test for both scenarios. Should have an answer in a day or two.

**Comment by ScriptJunky** [comment]
Test Setup:
Individual test.lua for just this user, with 75 messages in the INBOX.
After first test the same messages were moved back to the INBOX for test 2.

### test1-stacked
```lua
sender = account1["INBOX"]:contain_from("user@domain.com") *
         account1["INBOX"]:match_from("(?i)\\buser@domain.com\\b")
sender:move_messages(account1["[GROUPS]/User"])
```

```
Processing groups/test1-stacked
75 messages moved .....

real	5m58.461s
user	0m1.681s
sys	0m1.107s
```

### test1-meta
```lua
sender = account1["INBOX"]:contain_from("user@domain.com"):match_from("(?i)\\buser@domain.com\\b")
sender:move_messages(account1["[GROUPS]/User"])
```

```
Processing groups/test1-meta
75 messages moved .....

real	0m3.935s
user	0m0.046s
sys	0m0.027s
```

**Comment by lefcha** [comment]
Well the difference is huge, and if you have hundreds or thousands of messages in your inbox, then the stacked way of filtering would need to downloads the `From:` header field from all of them, while with meta-searching you just download only from the 75 messages that are relevant.

**Comment by ScriptJunky** [comment]
Coolness. In the interest of full disclosure, the INBOX had less than 10k items, but hey, if it works it works!

# Thanks!
