### ISSUE TITLE
Timeout period expired (but server works 100% fine for other programs)

### ISSUE THREAD

**Issue by jocap** [lefcha/imapfilter#160]
Hello,

I've been trying to configure this program, as it seems to be exactly what I want, but I ran into a pretty big problem. For some reason, imapfilter can't connect to my IMAP server.

This is my configuration file:

```
account1 = IMAP {
   server = 'mail.webfaction.com',
   username = 'my_username',
   password = decrypt_pw(),
   port = 993
}
```

(The `decrypt_pw()` is a function of my own, but I've checked that it returns the correct password, and I've tried entering my password through the imapfilter command-line interface as well.)

When running `imapfliter -c my_config.lua`, nothing happens, until: 

```
Sat May 20 22:50:22 2017: timeout period expired while waiting to read data
Sat May 20 22:50:22 2017: login request to my_username@mail.webfaction.com failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/home/jocap/mail/local/share/imapfilter/account.lua:81: in field '_check_result'
	/home/jocap/mail/local/share/imapfilter/account.lua:97: in field '_login_user'
	/home/jocap/mail/local/share/imapfilter/account.lua:59: in global 'IMAP'
	filter.lua:13: in main chunk
```

If I run `openssl s_client -host mail.webfaction.com -port 993 -crlf`, I can see that it returns an OK and everything looks fine. Other programs, like `mbsync` and my e-mail client, are able to access `mail.webfaction.com` just fine.

The debug and log files contain no other information, unfortunately. Maybe it's that I'm connecting from a Webfaction server? I don't know, that shouldn't matter, right? Anyhow, I would really appreciate some help. There don't seem to be many other tools for filtering remote e-mail.

*Update:* I suppose I'll mention that I tried turning up the timeout period to 120 seconds, but still, no results.
*Update 2:* I installed Lua and imapfilter on my personal machine as well to try it there, but still the same result. Very weird, as I use `mbsync` to connect to the server from this machine without any problems.

**Comment by lefcha** [comment]
This is very strange indeed, it's like the server doesn't respond and the client (imapfilter) times out.

Does it make any difference if you don't specify a password in the configuration file, and so let imapfilter ask for one?

Also, in the debug log, you don't see anything after the `LOGIN` request by imapfilter?

**Comment by jocap** [comment]
Yes, it is very strange! I can confirm it's not a server issue, because I have tried it with another mail server as well and gotten the same results.

I've tried manually entering the password as you describe, but it makes no difference. When I run `imapfilter -c filter.lua -d debug` and look at `debug`, it is completely empty.

Maybe there's something I'm doing wrong - I did compile Lua and imapfilter both from source. I don't necessarily need imapfilter anymore as I've implemented filtering with Sieve on my server, but it seems like a very nice tool.

**Comment by lefcha** [comment]
Can you include your config, or a the small subset of it you're trying to run?

**Comment by ncadou** [comment]
I see something that looks similar, with 2.6.10 on alpine 3.6. In my case it seems to hang forever on STARTTLS, even ignoring the 10s timeout option.

Command:
`imapfilter -c /tmp/config.lua -d /tmp/dbg`

`/tmp/config.lua`:
```
# vi: ft=lua

print('*** before')

options.timeout = 10

mbox = IMAP {
    server = 'mail.webfaction.com',
    username = '***',
    password = '***',
}

print('*** after')
```

Console output:
```
*** before
Server certificate subject: /CN=*.webfaction.com/O=Paragon Internet Group Ltd/L=Slough/ST=Berkshire/C=GB
Server certificate issuer: /C=US/ST=Illinois/L=Chicago/O=Trustwave Holdings, Inc./CN=Trustwave Organization Validation SHA256 CA, Level 1/emailAddress=ca@trustwave.com
Server certificate serial: 06A836FDD51B1B49AD03BADF3D066C3B2BA71A
Server key fingerprint: 92:4C:D8:3D:B7:39:85:F4:93:4E:DF:1D:0C:A0:0E:CC
```

`/tmp/dbg`:
```
getting response (4):

* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN] Dovecot ready.

sending command (4):

1000 NOOP

getting response (4):

1000 OK NOOP completed.

sending command (4):

1001 CAPABILITY

getting response (4):

* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN
1001 OK Pre-login capabilities listed, post-login capabilities have more.

sending command (4):

1002 STARTTLS

getting response (4):

1002 OK Begin TLS negotiation now.
```

**Comment by lefcha** [comment]
When I use the exact config by @ncadou, leaving `***` for the username and password to see how far it will go, I get through the TLS negotiation, and then it fails in the authentication:

```
*** before
S (3): * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN] Dovecot ready.
C (3): 1000 CAPABILITY
S (3): 1000 OK Pre-login capabilities listed, post-login capabilities have more.
C (3): 1001 STARTTLS
S (3): 1001 OK Begin TLS negotiation now.
C (3): 1002 CAPABILITY
S (3): 1002 OK Pre-login capabilities listed, post-login capabilities have more.
C (3): 1003 LOGIN "***" *
S (3): 1003 NO [AUTHENTICATIONFAILED] Authentication failed.
imapfilter: IMAP (3): 1003 NO [AUTHENTICATIONFAILED] Authentication failed.
imapfilter: username *** or password rejected at mail.webfaction.com
imapfilter: authentication of ***@mail.webfaction.com failed.
```

And the debug log:

```
getting response (4):

* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN] Dovecot ready.

sending command (4):

1000 NOOP

getting response (4):

1000 OK NOOP completed.

sending command (4):

1001 CAPABILITY

getting response (4):

* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN
1001 OK Pre-login capabilities listed, post-login capabilities have more.

sending command (4):

1002 STARTTLS

getting response (4):

1002 OK Begin TLS negotiation now.

sending command (4):

1003 CAPABILITY

getting response (4):

* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN
1003 OK Pre-login capabilities listed, post-login capabilities have more.

sending command (4):

1004 LOGIN "***" *

getting response (4):

1004 NO [AUTHENTICATIONFAILED] Authentication failed.
```

**Comment by ncadou** [comment]
Well, that's interesting! Which OS/Python interpreter versions did you use? Ubuntu 16.04 with stock Python 2.7 on my side.

**Comment by lefcha** [comment]
Hm, I'm using Debian 9.2 (stretch), which should be similar to Ubuntu 16.04...

**Comment by ncadou** [comment]
Got my storylines mixed up, it's got nothing to do with Ubuntu or Python, the error was on alpine 3.6. But you got me thinking and I found the problem. It's embarrassing, but the alpine installation was simply missing the ca-certificates package, it works fine now. Sorry for the noise!
