### ISSUE TITLE
imapfilter doesn't build with libressl

### ISSUE THREAD

**Issue by improbability** [lefcha/imapfilter#161]
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make all
cc -o imapfilter -L/opt/local/lib  auth.o buffer.o cert.o core.o file.o imapfilter.o list.o log.o lua.o memory.o misc.o namespace.o pcre.o regexp.o request.o response.o session.o signal.o socket.o system.o -lm -ldl -llua -lpcre -lssl -lcrypto 
Undefined symbols for architecture x86_64:
  "_HMAC_CTX_free", referenced from:
      _auth_cram_md5 in auth.o
  "_HMAC_CTX_new", referenced from:
      _auth_cram_md5 in auth.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [imapfilter] Error 1
make: *** [all] Error 2

Following diff 'fixes' this.
diff --git a/src/auth.c b/src/auth.c
index 99e3a09..9ab3492 100644
--- a/src/auth.c
+++ b/src/auth.c
@@ -20,7 +20,7 @@ auth_cram_md5(const char *user, const char *pass, unsigned char *chal)
 	unsigned char *resp, *buf, *out;
 	unsigned char md[EVP_MAX_MD_SIZE], mdhex[EVP_MAX_MD_SIZE * 2 + 1];
 	unsigned int mdlen;
-#if OPENSSL_VERSION_NUMBER >= 0x1010000fL
+#if OPENSSL_VERSION_NUMBER >= 0x1010000fL && !defined(LIBRESSL_VERSION_NUMBER)
 	HMAC_CTX *ctx;
 #else
 	HMAC_CTX ctx;
@@ -32,7 +32,7 @@ auth_cram_md5(const char *user, const char *pass, unsigned char *chal)
 
 	EVP_DecodeBlock(resp, chal, strlen((char *)(chal)));
 
-#if OPENSSL_VERSION_NUMBER >= 0x1010000fL
+#if OPENSSL_VERSION_NUMBER >= 0x1010000fL && !defined(LIBRESSL_VERSION_NUMBER)
 	ctx = HMAC_CTX_new();
 	HMAC_Init_ex(ctx, (const unsigned char *)pass, strlen(pass),
 	    EVP_md5(), NULL);

Scuze the laziness of not forking/pulling -- Under time pressue.

**Comment by lefcha** [comment]
Closed by c1865ba1ab2fd8da14e5e018ab55c79cbc432295.
