### ISSUE TITLE
question: is there a way to simply print some mail fields?

### ISSUE THREAD

**Issue by theist** [lefcha/imapfilter#162]
note: almost complete lua iliterate asking...

I would like to use some imapfilter configs to preview or extracts my inbox mail senders so I can manually build an array of senders to delete without manualy wander in my inbox

I know how to delete an array of senders with code like

```
senders = {
  'foo@',
  '@bar',
  'baz'
}

for i, sender in ipairs(senders) do
  print("Delete from " .. sender)
  messages = mail.INBOX:contain_from(sender)
  messages:delete_messages()
end
```

But I do not know how I can (if I can) use imapfilter to print the existing list of senders in my inbox.

Is there a way to do some listings on messages retrieved?

**Comment by lefcha** [comment]
Try something like that to print an all unique senders list (it might take some time if you have a lot of messages):

```lua
mail = IMAP {
    ...
}

all = mail.INBOX:select_all()
senders = {}
for _, msg in ipairs(all) do
    mbox, uid = unpack(msg)
    from = mbox[uid]:fetch_field('From')
    senders[from] = true
end
for sender in pairs(senders) do print(sender) end
```

**Comment by theist** [comment]
Thanks! 

Closing
