### ISSUE TITLE
options.limit does not work for `select_all()`

### ISSUE THREAD

**Issue by AloisMahdal** [lefcha/imapfilter#165]
IIUC, all actions sould be affected by the `options.limit` clause, but when I have, say, 800 messages and use `select_all()`, imapfilter still seems to access all 800 messages, which is a breaking performance issue in my use case.

IOW, verbose mode shows log like this:

    S (4): * OK IMAP4 ready
    C (4): 1000 NOOP
    S (4): 1000 OK completed
    C (4): 1001 CAPABILITY
    S (4): 1001 OK completed
    C (4): 1002 LOGIN "redacted" *
    S (4): 1002 OK [CAPABILITY IMAP4rev1 redacted] LOGIN completed
    C (4): 1003 CAPABILITY
    S (4): 1003 OK CAPABILITY completed
    C (4): 1004 NAMESPACE
    S (4): 1004 OK NAMESPACE completed
    C (4): 1005 STATUS "FILTER_QUEUE" (MESSAGES RECENT UNSEEN UIDNEXT)
    S (4): 1005 OK STATUS completed
    C (4): 1006 SELECT "FILTER_QUEUE"
    S (4): 1006 OK [READ-WRITE] SELECT completed
    C (4): 1007 UID SEARCH ALL
    S (4): 1007 OK UID SEARCH completed
    C (4): 1008 UID FETCH 781880 BODY.PEEK[HEADER]
    S (4): 1008 OK UID FETCH completed
    C (4): 1009 UID FETCH 781881 BODY.PEEK[HEADER]
    S (4): 1009 OK UID FETCH completed
    C (4): 100A UID FETCH 781885 BODY.PEEK[HEADER]
    S (4): 100A OK UID FETCH completed
    C (4): 100B UID FETCH 781890 BODY.PEEK[HEADER]
    S (4): 100B OK UID FETCH completed
    ...

with the last two lines repeating 800 times, even though I set `options.limit = 50`.

imapfilter version is IMAPFilter 2.6.7, built from master as of commit 23a3c62. Running on Debian 8.8.

**Comment by lefcha** [comment]
The `options.limit` is used for something completely different; it's for long requests not for many requests.

If imapfilter tries to fetch the header of so many messages, it means you are trying to do local matching of all these messages, using one of the `match_*()` methods.  I suggest using one of `contain_*()` methods instead (does the matching remotely) or try to limit the messages your matching using meta-searching. All the above are documented in the `imapfilter_config(5)` man page.

**Comment by AloisMahdal** [comment]
Thank you for explanation, I see I misunderstood the feature.

Anyway, what I'm trying to do in my imapfilter script is actually "take first 50 messages" (the "first" being in the arbitrary meaning, like "any 50 messages"), then I want to perform set of useful rules. For example:

    x = box.select_all()
    m = x:match_subject('^foo: ')
    m:move_messages('somewhere/else')

The problem is that while I normally run this every few minutes (from work laptop), sometimes I skip lot of runs and the queue can get really huge.  Last time this happened, the queue was thousdands of e-mails, and the mail server not being of the fastest, my rules took hours to finish.

So what I really wanted to do (and was expecting `options.limit` to do for me) was tweaking the `select_all()` to only select N messages at most.  That way, I could handle huge queues by simply re-running the script multiple times (or letting it catch up).

About `contain_*()`, it's good to know that, but some messages I get are poorly formed so regex really looks like better tool. And regarding meta-searching, I thought about it but could not come up with any strategy.

So is there a proper solution?  What about adding something like `select_last(N)`?

**Comment by AloisMahdal** [comment]
Also, an off-topic did you consider running (and mentioning in README.md) an official IRC/reddit/... channel? As a Software QE, It hurts me to abuse Github issues for questions. :)

Or even Patreon (I've used imapfilter for years now and I rely on it so much that I'd definitely feel like supporting it)?

**Comment by lefcha** [comment]
Try getting the latest imapfilter from GitHub, and then try the following:

```lua
options.limit = 10
options.range = 10
```

The `range` option was recently added, and you read what exactly it does in the discussion of issue #132.

The above values should make it break requests to run for every 10-100 messages (this is based on whether the messages UIDs are consecutive or not).  You can experiment with the values.

For example if you are sure all messages are new and thus have consecutive UIDs, so imapfilter would run a request for example for 1000 messages (UIDs 5500-6500), by setting `options.limit = 1` and `options.range = 50`, you make sure it will break this in 20 requests to be run for 50 messages each time.

If that is not enough, then you can just run a for loop similar to many examples in [extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua), copy 50 messages from the result of `select_all()` to a new table, and call a function on the new table.  You could also easily write a generic function to do that.

**Comment by lefcha** [comment]
I used to have a mailing list, but I myself mostly answered all questions, so I decided to use the issues tracker of GitHub instead.  It's OK to use it for questions in addition to bugs, as the volume is not so much to have some more fine grained tracker.

Patreon is nice, but I'm not able to put much work on it anymore due to lack of time, and the current implementation is mostly stable/mature, so probably it doesn't make sense to be subscribed to it to help me work on it.  A couple of people have sent me a symbolic donation in PayPal in the past, but I never ask for any, as the fact that it has been and is useful to people is great alone.

**Comment by AloisMahdal** [comment]
Sorry for taking so long to reply.

I tried to set `options.limit` and `options.range` to 1, but it did not have the effect I anticipated; single imapfilter call with file like this:

    x = am['Junk']:select_all()
    x = filter_header_saved(x, 'am-Junk')     # fetch_header() + save to file
    x:delete_messages()

would still process whole queue (UIDs were consecutive, if that matters).

Anyway, I think I'll look into extend.lua and try to implement some sort of `head` or `tail` myself, so feel free to close this issue.  (I do feel "native" head/tail would be useful in imapfilter so I might open another RFE issue with proper justification.)

**Comment by lefcha** [comment]
The `limit` and `range` options are used only in when copying/moving or flagging messages.

So in this case if you do a `match_header()` on all messages they should not make a difference.

So my suggestion is to take the results of select_all() and have some simple Lua function that will break these in smaller chunks.  You can take like 10 of them from the results, put them in a new partial result set (there are a lot of examples in the [extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua) file), and then process these smaller chunks.
