### ISSUE TITLE
SSL verification not working as expected?

### ISSUE THREAD

**Issue by djl** [lefcha/imapfilter#166]
There seems to be an issue with verifying SSL certificates against the system certificates. Without specifying the path to a specific file it seems that imapfilter can't find any CA files.

For example:

    $ imapfilter
    Server certificate subject: /C=US/ST=California/L=Mountain View/O=Google Inc/CN=imap.gmail.com
    Server certificate issuer: /C=US/O=Google Inc/CN=Google Internet Authority G2
    Server certificate serial: 6BDD52FEC4959C67
    Server key fingerprint: C6:E5:E8:EE:04:2B:76:1D:48:B5:05:B4:71:03:C9:6B
    (R)eject, accept (t)emporarily or accept (p)ermanently? 

However if I pass the full path to my system's CA bundle, it works:

    $ imapfilter -t /etc/ssl/certs/ca-bundle.crt
    ... snip ...

If it matters, this happens on my CentOS 7 and Debian 8/9 boxes.

Is this a bug or am I overlooking something obvious, like a way to specify the trust store in my config file?

**Comment by Papafox** [comment]
In the imapfilter script, do you have a truststore attribute for the gmail
account?  For example, I use:

wsadmin = IMAP {
    server     = 'imap.gmail.com',
    username   = 'matthew@xxxxxx.xxx',
    password   = 'xxxxxxxxxxxxxxxxxx',
    port       =  993,
    ssl        = 'tls12',
    truststore = '/etc/ssl/certs'
}

Truststore should default to '/etc/ssl/certs'.  Try setting truststore to '
/etc/ssl/certs/ca-bundle.crt'

Matthew







————————————————————————————————————————————————————
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by djl** [comment]
No luck with setting truststore to either `/etc/ssl/certs` or `/etc/ssl/certs/ca-bundle.crt`. It seems the truststore attribute is ignored entirely. It only works if I specify the full path to the file with `-v` option.

Something strange is going on, though. strace shows something (OpenSSL, I'm guessing) looking for non-existent files under /etc/ssl/certs;

    $ strace imapfilter -n 2>&1 | grep ssl/certs
    access("/etc/ssl/certs", F_OK)          = 0
    stat("/etc/ssl/certs", {st_mode=S_IFDIR|0755, st_size=134, ...}) = 0
    access("/etc/ssl/certs", F_OK)          = 0
    stat("/etc/ssl/certs", {st_mode=S_IFDIR|0755, st_size=134, ...}) = 0
    stat("/etc/ssl/certs/3513523f.0", 0x7ffde9d4bfc0) = -1 ENOENT (No such file or directory)
    stat("/etc/ssl/certs/f39fc864.0", 0x7ffde9d4bfc0) = -1 ENOENT (No such file or directory)
    stat("/etc/ssl/certs/578d5c04.0", 0x7ffde9d4bfc0) = -1 ENOENT (No such file or directory)
    stat("/etc/ssl/certs/578d5c04.0", 0x7ffde9d4bfc0) = -1 ENOENT (No such file or directory)

Looks like I'll need to debug my OpenSSL install.

**Comment by Papafox** [comment]
I'm mot a RHEL expert, but don't you need to run the update-ca-trust
command?

Matthew






————————————————————————————————————————————————————
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by djl** [comment]
After a bit of research I discovered that this a long-standing [RHEL bug](https://bugzilla.redhat.com/show_bug.cgi?id=1053882) that doesn't look like it's going to be fixed any time soon.

This could be fixed for RHEL users if we could specify trust store somewhere in the config file, either globally (e.g `options.truststore`) or individually for each account.

For now I can specify the trust store via the command line.

**Comment by Papafox** [comment]
The truststore option for an account can accept either a directory or a
file, so try something like:

wsadmin = IMAP {
    server     = 'imap.gmail.com',
    username   = 'matthew@xxxxxx.xxx',
    password   = 'xxxxxxxxxxxxxxxxxx',
    port       =  993,
    ssl        = 'tls12',
    truststore = '/etc/ssl/ca-bundle.crt'
}

should fix the problem.

Matthew







————————————————————————————————————————————————————
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by djl** [comment]
That doesn't seem to work for me running 2.6.10. Here's my config:

    gmail = IMAP {
      server = 'imap.gmail.com',
      username = 'xxx',
      password = 'xxx',
      ssl = 'auto',
      truststore = '/etc/ssl/certs/ca-bundle.crt',
    }

imapfilter never looks for that file:

    open("/lib64/libssl.so.10", O_RDONLY|O_CLOEXEC) = 3
    access("/etc/ssl/certs", F_OK)          = 0
    stat("/etc/ssl/certs", {st_mode=S_IFDIR|0755, st_size=117, ...}) = 0
    access("/etc/ssl/certs", F_OK)          = 0
    stat("/etc/ssl/certs", {st_mode=S_IFDIR|0755, st_size=117, ...}) = 0
    stat("/etc/ssl/certs/3513523f.0", 0x7ffffbb50850) = -1 ENOENT (No such file or directory)

But it does exist:

    $ ls -l /etc/ssl/certs/ca-bundle.crt
    lrwxrwxrwx. 1 root root 49 Jul 24 16:00 /etc/ssl/certs/ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

**Comment by maikell** [comment]
I can reproduce some of 'unwanted' behaviour'

Server is:  CentOS Linux release 7.3.1611 (Core) 
Version: imapfilter-2.5.6-1.el7

```
     account4 = IMAP {                                                        
     server = 'mail.*.net',                                           
     username = '*@*.net',                                        
     password = '*',                                            
     truststore= '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem'      
     }                                                                        
```                                                                       
Executing imapfilter I run into the question

```
(R)eject, accept (t)emporarily or accept (p)ermanently?
```
This TLS cert is from Let's Encrypt and every 90 day's (or less) this requests a manual action, taking me by surprise, since imapfilter runs each 10 minutes with a cronjob.

**Comment by lefcha** [comment]
Hm, there's no `truststore` option for the accounts inside imapfilter's config file, unless you're using some fork that has this.

The way to set the truststore is using the command line option, something like `imapfilter -t /path/to/truststore/dir_or_file.pem`.  This is documented in the `imapfilter(1)` man page:

>      -t truststore
>             The path to the system's SSL CA TrustStore directory or file. SSL
>             connections will be validated using the CA certificates found in
>             this directory or file, and when this is not possible the local
>             $HOME/.imapfilter/certificates file will be used.  The default is
>             either the /etc/ssl/certs directory or the /etc/ssl/cert.pem
>             file, whichever is found.
