### ISSUE TITLE
Option to interrupt IDLE (enter_idle()) without "killed by signal" message

### ISSUE THREAD

**Issue by igorakkerman** [lefcha/imapfilter#167]
Hi Lefteris, 

First of all, thanks for your great work creating and maintaining Imapfilter.

Is there a way to interrupt the `enter_idle()` call except from sending a signal like SIGTERM? The idea is to restart Imapfilter with an updated configuration script. It would be nice not to see a message like "imapfilter: killed by signal 15" in the logs in that case.

Cheers,
Igor

**Comment by lefcha** [comment]
First, thanks a lot! :-)

Now, there is no such functionality at the moment.  In theory breaking IDLE mode with a signal should not be hard to implement, but reloading the configuration might be more tricky.  What exactly do you have in mind? It might not be that difficult and I could implement this.

**Comment by igorakkerman** [comment]
To get started, it would be great to have an option to not print signal messages like "imapfilter: killed by signal 15", which is a bit misleading in the logs. Something like:
`options.signalinfo = false`

The idea is to be able to update the Imapfilter configuration script  on the server
I run Imapfilter in a loop from a shell script. Imapfilter connects to the server and remains in IDLE mode. Another script, the configuration update processor, runs in the background. Whenever the configuration script is updated, Imapfilter is killed (SIGTERM) by the configuration update processor. The message "imapfilter: killed by signal 15" is printed, the process terminates and gets restarted from the loop. Now it uses the updated configuration script.

Maybe you can help me out with some smarter solution.

**Comment by lefcha** [comment]
I just remembered that reloading the config could be done just with some Lua code.  Here's a post of mine from 3 years ago that you could try:

https://github.com/lefcha/imapfilter/issues/73#issuecomment-60685208

If this works for you, you should not get any `killed by` error messages and you could have a way to reload the config whenever it is changed, without the need to stop-start imapfilter.

**Comment by igorakkerman** [comment]
As far as I understand, you're suggesting to use `dofile('config-aux.lua')` to load the additional configuration. Now, what if _config-aux.lua_ enters IDLE mode? How would it be interrupted, `dofile(...)` not being asynchronous?

**Comment by lefcha** [comment]
Yes, you're right, I forgot about IDLE.  I need to add support for interrupting IDLE possibly with `SIGUSR1` or something, or make it a generic/special way to interrupt any networking command that might block, and ignore this signal in all other cases.

**Comment by lefcha** [comment]
This commit https://github.com/lefcha/imapfilter/commit/09e0043b994c7b1e79acbcb7b2197178922af1bf implements support for interrupting IDLE mode by sending a SIGUSR1 or SIGUSR2 signal to imapfilter.  The configuration then continues from the next line after `enter_idle()`, and also in this case `enter_idle()` returns just a single value `true` without a second value indicating the event.

Let me know if that is OK, thanks!

**Comment by lefcha** [comment]
Even better pull the latest from master, as commit https://github.com/lefcha/imapfilter/commit/7ae13a12bcf3c1a9e380b56a22a0aa0178da849a does some related improvements.

**Comment by igorakkerman** [comment]
Thanks so much! I will let you know as soon as I have tried it out. 

This might take some time because it would currently require me to modify the Dockerfile to pull from the Git repo. Currently I'm installing it inside of an Ubuntu container using `apt-get`. Also, at the moment, it takes a set of manual steps to deploy it in the destination environment... 

If you're confident enough to create a new release, I could try it out much faster. But probably, there's no need to rush.

**Comment by lefcha** [comment]
Just released 2.6.11, but I'm not sure when you'll get it packaged in distributions...

**Comment by igorakkerman** [comment]
Thank you! I'm using the latest Ubuntu as base image. Release 2.6.11 has not yet been made available through their repositories. Do you know who's taking care of the imapfilter upstream?
https://wiki.ubuntu.com/Upstream

**Comment by lefcha** [comment]
Hm, probably it's one of the packages they get from Debian, so probably it has to be updated in Debian first.

**Comment by igorakkerman** [comment]
I was able to setup 2.6.11 and trigger the interruption of IDLE mode using SIGUSR1. It works like a charm, thanks a lot!

I noticed that the repositories of Ubuntu "bionic" already provided version 2.6.11, so I upgraded my base image.

**Comment by lefcha** [comment]
That's great to hear, thanks for testing this!
