### ISSUE TITLE
Messages lost after moving to "Mailboxes/"

### ISSUE THREAD

**Issue by cmantsch** [lefcha/imapfilter#168]
I am filtering mails by incoming mail address into separate submailboxes:

```
messages = account.INBOX:contain_to("foo@mydomain.com") - account.INBOX:is_unseen()
messages:move_messages(account["Mailboxes/foo"])
```

I accidentally executed the command without any sub mailbox name as follows
`messages:move_messages(account["Mailboxes/"])`

It moved several messages marked as seen to "Mailboxes/", but I can't find them in this Mailbox in my client.
Where can I find them?

**Comment by lefcha** [comment]
Have you tried doing a `account["Mailboxes/"]:select_all()` to see whether they are there, as the server might also make it possible to store messages there.

Other than that have also a a look at the `list_all()` method, as you can at least have a look at the available mailboxes with that.
