### ISSUE TITLE
Exception uncaught on initiating SSL Connection

### ISSUE THREAD

**Issue by internationils** [lefcha/imapfilter#169]
Hello, 

I got this exception, it should probably be caught and handled gracefully (N retries, then fail?) It was probably due to a reboot of my mailserver.
```
imapfilter: initiating SSL connection to localhost; Connection reset by peer
imapfilter: idle request to myuser@localhost failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/usr/local/share/imapfilter/mailbox.lua:46: in function '_check_result'
	/usr/local/share/imapfilter/mailbox.lua:1069: in function 'enter_idle'
	/home/myuser/.imapfilter/config.lua:505: in main chunk
```

**Comment by lefcha** [comment]
Is `options.recover` enabled in your config? With that you should get one retry in case of a failed command.

Also, what about `options.persist`? If you want more than one retries you could try to enable this one, too.
