### ISSUE TITLE
Problem with oauth2

### ISSUE THREAD

**Issue by dgiglio** [lefcha/imapfilter#171]
Hi,
I've got a problem trying to access GMail with oauth2, the following code returns the error:
`config.lua:39: attempt to concatenate global 'accesstoken' (a nil value)`

Where line 39 is
`status, output = pipe_from('oauth2.py --generate_oauth2_string' ..
                           ' --access_token=' .. accesstoken ..
                           ' --user=' .. user)`

I don't know LUA but I suspect the problem is here:
`_, _, accesstoken = string.find(output, 'Access Token: ([%w%p]+)\n')`

If I invoke oauth2.py directly in the command line it works correctly.
Thanks in advance.

**Comment by lefcha** [comment]
What is the output when you run the command in the command line? Remove all sensitive strings before copy/pasting here...

**Comment by dgiglio** [comment]
my input:

`oauth2.py --client_id=[...] --client_secret=[...] --refresh_token=[...]`

its output:

`Access Token: [...]`
`Access Token Expiration Seconds: 3600`

**Comment by dgiglio** [comment]
1.
`oauth2.py --generate_oauth2_token --client_id=[...] --client_secret=[...]`
To authorize token, visit this url and follow the directions:
  https://accounts.google.com/o/oauth2/auth?client_id=[...]redirect_uri=[...]response_type=code&scope=https%3A%2F%2Fmail.google.com%2F
`Enter verification code: [...]`
`Refresh Token: [...]`
`Access Token: [...]`
`Access Token Expiration Seconds: 3600`

2.
--> `oauth2.py --generate_oauth2_string --access_token='[....]' --user='*******@gmail.com'`
<-- `OAuth2 argument:[...]`

**Comment by dgiglio** [comment]
code snippet:

status, output = pipe_from('oauth2.py --client_id=' .. clientid ..
			   ' --client_secret=' .. clientsecret ..
			   ' --refresh_token=' .. refreshtoken)
_, _, accesstoken = string.find(output, 'Access Token: ([%w%p]+)\n')

status, output = pipe_from('oauth2.py --generate_oauth2_string' ..
                           ' --access_token=' .. accesstoken ..
                           ' --user=' .. user)
_, _, oauth2string = string.find(output, 'OAuth2 argument:\n([%w%p]+)\n')

**Comment by lefcha** [comment]
Hm, strange output looks OK in command line.

Try to print the output inside your configuration file.  After line 39 add a `print()` statement like this:

```lua
status, output = pipe_from('oauth2.py --generate_oauth2_string' .. ' --access_token=' .. accesstoken .. ' --user=' .. user)
print(status, output)
```

What do you get?

**Comment by dgiglio** [comment]
Nothing, I suspect the error is in `pipe_from()`

**Comment by dgiglio** [comment]
I also tried this:
`status, output = pipe_from('oauth2.py --client_id=' .. clientid .. ' --client_secret=' .. clientsecret ..' --refresh_token=' .. refreshtoken)`
`print(status,output)`

It returns 1, output is empty. The second `pipe_from()` fails to execute.

**Comment by lefcha** [comment]
A status of `1` probably means the `oauth2.py` command failed for some reason...

Try to print the exact command that is passed to `pipe_from()`, and then copy/paste that in your shell, to see whether it works fine:

```lua
print('oauth2.py --client_id=' .. clientid .. ' --client_secret=' .. clientsecret ..' --refresh_token=' .. refreshtoken
```

Maybe there's something in those variables causing the command to fail.

**Comment by dgiglio** [comment]
File "/usr/local/bin/oauth2.py", line 335, in <module>
    main(sys.argv)
  File "/usr/local/bin/oauth2.py", line 301, in main
    options.refresh_token)
  File "/usr/local/bin/oauth2.py", line 232, in RefreshToken
    response = urllib.urlopen(request_url, urllib.urlencode(params)).read()
  File "/usr/lib/python2.7/urllib.py", line 89, in urlopen
    return opener.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 215, in open
    return getattr(self, name)(url, data)
  File "/usr/lib/python2.7/urllib.py", line 460, in open_https
    data)
  File "/usr/lib/python2.7/urllib.py", line 379, in http_error
    result = method(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 689, in http_error_401
    errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0xb6720fa8>)

**Comment by dgiglio** [comment]
Sincerely, reading at oauth2.py help, I don't understand which operation the statement 
`oauth2.py --client_id=[...] --client_secret=[...] --refresh_token=[...]`
should perfom

**Comment by lefcha** [comment]
This command gets you a new valid access token, as those expire after a while.  The refresh token is used for that purpose, ie. to refresh your access token.  So the server returns the new access token, and you can use that to access your data.

I would suggest to start the process all over, and first try to do it from the command line using the `oauth2.py` script and instructions in [OAuth2DotPyRunThrough](https://github.com/google/gmail-oauth2-tools/wiki/OAuth2DotPyRunThrough).  Hopefully, these are still relevant and nothing changed on the API level, or the script isn't broken...
