### ISSUE TITLE
Is it possible to use imapfilter to provide Boomerang-like support?

### ISSUE THREAD

**Issue by numist** [lefcha/imapfilter#174]
Given a message, is there an efficient way to query for any responses to that message?

I am trying to figure out a good way to automatically send myself a reply when a conversation I've initiated/responded to has gone idle after some number of days. Preferably I could enable this with a special sequence/header in the message but piece I'm missing if I'm to do this with imapfilter is navigating the conversation's messages.

**Comment by lefcha** [comment]
In theory it could be possible to do this, by investigating emails in the last week or so in your inbox, and for each message try to search a reply in your sent folder.  I could think of two ways to verify whether a reply exists:

1. For a message in inbox with a specific subject and date, you search for messages that are newer that the date of the message in inbox, and that have the same subject as the message in inbox.

2. For a message in inbox with a specific `Message-ID` header value, you search for messages that have the same value in their `In-Reply-To` header.  This is based on the fact that when you reply to a message, your reply has a `In-Reply-To` header set to the `Message-ID` of the message you reply to.

There could possibly be more ways to do that, just some ideas that crossed my mind.  In any case you can have imapfilter search for messages you didn't reply this way, and then mark them as unread so you notice them, or possibly add a star to them, etc.

**Comment by numist** [comment]
Ah thank you, the `In-Reply-To` header was the piece I was missing.
