### ISSUE TITLE
contain_to doesn't match when it (obviously?) should

### ISSUE THREAD

**Issue by maxf130** [lefcha/imapfilter#175]
The following contain_to:

    f_account.Inbox:contain_to("ibers-all@aber.ac.uk")

doesn't match a message containg the follwing To field:

    To: "'ibers-all@aber.ac.uk'" <ibers-all@aber.ac.uk>

Hovever `f_account.Inbox:contain_to("ibers-all@aber.ac")` matches the same message just fine.  Given that the searching happens on the server and not locally, I guess this is a server side issue.  I post it just in case.

Many Thanks

**Comment by lefcha** [comment]
It looks like a problem with the server search, but check what is the status of the response for this specific search request (`OK`, `BAD`, or `NO`), by using the `-v` or the `-d debug.log` arguments.

**Comment by maxf130** [comment]
I was getting an `OK` response.  

A workaround for me was to use `f_account.Inbox:is_unseen():match_to("ibers-all@aber\\.ac\\.uk")` instead.  I don't receive enough mail for the reduced performance of the local regex matching to be a problem.
