### ISSUE TITLE
Add some more documentation, on how to access the data

### ISSUE THREAD

**Issue by klartext** [lefcha/imapfilter#176]
Hi,

nice tool.
But reading the docs does not help so much...
... some overview on the data structures and functionality would be nice.

Otherwise it's rather a riddle in reverse engineering...

**Comment by lefcha** [comment]
Some of the return values are mentioned in the man page, but the format of the messages returned from the search function can possibly be understood from the [extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua).  It's basically a table containing tables with 2 elements: (a) the mailbox where the message belongs and (b) the message UID.

I'll see if I can add a small note explaining this somewhere in the man page...

**Comment by lefcha** [comment]
Closed by https://github.com/lefcha/imapfilter/commit/228d208919d4c6f34d23d2aed9ff4b985fbeffcc.
