### ISSUE TITLE
Can't use Mailbox with an Umlaut in them

### ISSUE THREAD

**Issue by NWuensche** [lefcha/imapfilter#180]
Hello,

I want to delete messages in my account `acc1` and mailbox called `Unerwünscht`. But when I try to do something like `acc1.Unerwünscht:contain_from('email@mail.com')`, I just get the error 'unexpected symbol near char(195)' on this line.

But when I print all Mailboxes from acc1, it doesn't have any problems printing 'Unerwünscht'. I also tried to set `options.charset = 'UTF-8'`, but this didn't change the error message.

Can anyone please help me? I'm using 2.6.10 on Ubuntu 17.10

**Comment by sioh** [comment]
Use `acc1['Unerwünscht']:contain_from('email@mail.com')` instead.

**Comment by NWuensche** [comment]
Thanks!
