### ISSUE TITLE
Document use of enter_idle

### ISSUE THREAD

**Issue by MaZderMind** [lefcha/imapfilter#181]
Following the basic examples in `config.lua` imapfilter does a search-action-terminate run and needs to be started externally. From the manpage it becomes clear that the IMAP IDLE-Extension can be used by calling `enter_idle`. This seems like a Feature important enough to me, to dedicate an example configuration for it.

**Comment by lefcha** [comment]
Good point, I'll add one.

**Comment by lefcha** [comment]
Closed by 22bb48ef030d3db516b7eeeae283f82d2933d156.
