### ISSUE TITLE
Make wildcard filters possible

### ISSUE THREAD

**Issue by maikell** [lefcha/imapfilter#182]
Is it possible to filter on wildcards, i.e:   *@example.org. Cannot find this at the man pages.

**Comment by AloisMahdal** [comment]
The server-side filters (`contain_*()`) match on substrings, so given that e-mails must end with `>`, you could get away with something like this:

    q:contain_from('@example.org>')

The `>` assumption is probably wrong in general, although it's been my experience that most sane servers will format the field this way.

You could also get stronger filtering with PCRE using `match_*()` functions.

    q:match_to('.*@example.org\\b')    # \b is PCRE for word boundary, double slash bc Lua

Just be aware that these are implemented locally, ie. they cause FETCH of the header, so don't do it if the `q` can be long.

**Comment by lefcha** [comment]
Exactly as @AloisMahdal described it, thanks!
