### ISSUE TITLE
is enter_idle() supposed to get out of idle when a message is flagged?

### ISSUE THREAD

**Issue by mathroc** [lefcha/imapfilter#183]
I'm trying to make something that would copy starred messages to the Favorites folders. however it seems that flagging a message does not trigger the loop. is it the expected behavior ?

I have something like that:

```lua
function filter ()
    rcc.INBOX:is_flagged():copy_messages(mrcc.Favorites)
    -- ...
    m.INBOX:enter_idle()
end

while true do filter() end
```

but it only copies messages when a new message arrives

**Comment by lefcha** [comment]
Try to set `options.wakeonany = true` at the top of your config file:

> By enabling this option the IDLE command will return on any event that is received from the server, and not just on the “RECENT” and “EXISTS” events, that normally indicate the arrival of a new message.  Examples of other events are “FETCH”, which indicates that the details of a message (eg. its flags) have been modified, or “EXPUNGE”, which indicates that a message has been deleted.  This variable takes a boolean as a  value.  Default is “false”.

The server should probably send a `FETCH` when a message is flagged/unflagged...

**Comment by mathroc** [comment]
yes that works, thank you !
