### ISSUE TITLE
Date error in comment?

### ISSUE THREAD

**Issue by lober** [lefcha/imapfilter#187]
You said: 

IMAPFilter 2.6.12 - 03 Oct 2017
  - Support for Server Name Indication (SNI).
  - The searching methods return values are described in the config man page.
  - Example of using the enter_idle() function in the sample extend file.

Don't you mean "03-Oct-**2018**" ?

Not the most important thing in your code, of course!

**Comment by lefcha** [comment]
Indeed!

Closed by https://github.com/lefcha/imapfilter/commit/56619dc977ef4e7ee31e32b2da36cf781e9e5fa4.
