### ISSUE TITLE
SSL and TLS connection problem

### ISSUE THREAD

**Issue by Kudlaty01** [lefcha/imapfilter#190]
I am constantly having problems connecting to an imap server, even with different configurations:
- when I just set `ssl='tls1'` (same for different tls configurations as `tls12` and `ssl3`):
> `imapfilter: initiating SSL connection to poczta.interia.pl; error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol`

- when I set `port = 143`:
> `imapfilter: initiating SSL connection to poczta.interia.pl; error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

- when I additionally remove the `ssl` option and add `options.starttls = false` at the config beginning I just get information that username or password has been rejected following directly this informational message:
> `imapfilter: IMAP (3): 1001 NO STARTTLS required.`

[NeoMutt](https://github.com/neomutt/neomutt) connects to the server without problems. Even my own [tool](https://github.com/Kudlaty01/pymapfilter) written in python and using imaplib connects without any problems when using _SSLContext_ with _PROTOCOL_TLSv1_

**Comment by lefcha** [comment]
Hm, not sure what goes here, I suspect some SSL version that's not compatible with the build of imapfilter you're running.

I tried connecting to this IMAP server with `openssl s_client` and I get a similar error:

```
$ openssl s_client -host poczta.interia.pl -port 993 -crlf 
CONNECTED(00000003)
140468004709440:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../ssl/statem/statem_lib.c:1922:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 58 bytes and written 316 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

Not sure if also what it mentions about a certificate is the reason, too...

**Comment by entonio** [comment]
I got this problem when using imapfilter with Ubuntu 20.04 (on Windows... don't ask), using ssl3. The solution was to downgrade to Ubuntu 18.04. Both ubuntus were installed simply to use imapfilter, there's nothing in them other than `sudo apt-get update`,  `sudo apt-get install imapfilter`, and then running imapfilter. It's some problem with the impafilter+ubuntu 20.04 combo; what's more, there's folks complaining about a similar issue with connection to SQL Server (!) from ubuntu 20.04.
