### ISSUE TITLE
Run against localhost

### ISSUE THREAD

**Issue by Nudin** [lefcha/imapfilter#191]
I have dovecot running localy (with isync for syncronisation with online imap server). I wanted to run imapfilter with this dovecot. It fails with the following output:

```
Enter password for michi@127.0.0.1: 
imapfilter: login request to michi@127.0.0.1 failed
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        /usr/share/imapfilter/account.lua:81: in field '_check_result'
        /usr/share/imapfilter/account.lua:97: in field '_login_user'
        /usr/share/imapfilter/account.lua:59: in global 'IMAP'
```

I don't use TLS, since it's localhost only  – maybe that's the problem?

**Comment by lefcha** [comment]
I would suggest to try and login with telnet or openssl client to see if it works there.  For example:

```
$ telnet 127.0.0.1
1 login michi <password>
```

You should see `1 OK` if it succeeds.

You can also try it with SSL like this:

```
$ openssl s_client -host 127.0.0.1 -port 993 -crlf
1 login michi <password>
```

**Comment by Nudin** [comment]
Telnet works (I have to give a port ofcourse):
```$ telnet 127.0.0.1 143
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot ready.
1 login michi <password>
1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY LITERAL+ NOTIFY QUOTA] Logged in
```

Openssl doesn't since I didn't enabled it – it's just surving on localhost.

**Comment by lefcha** [comment]
In that case can you run imapfilter with something like `-d debug.log`, and check the debug output or post the relevant parts from it, so we can see what goes?
