### ISSUE TITLE
Error at compiling

### ISSUE THREAD

**Issue by furx** [lefcha/imapfilter#193]
I'm trying to compile from source, but make always shows me this error:

`root@neus:/tmp/imapfilter# make`
`cd src && make all`
`make[1]: Entering directory '/tmp/imapfilter/src'`
`cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o lua.o lua.c`
`lua.c:5:17: fatal error: lua.h: No such file or directory`
` #include <lua.h>`
`----------------^`
`compilation terminated.`
`<builtin>: recipe for target 'lua.o' failed`
`make[1]: *** [lua.o] Error 1`
`make[1]: Leaving directory '/tmp/imapfilter/src'`
`Makefile:2: recipe for target 'all' failed`
`make: *** [all] Error 2`

All required packages should be installed, distribution is Debian 9.

**Comment by Papafox** [comment]
Do you have liblua??-dev installed?

Matthew

**Comment by furx** [comment]
Yes,  liblua5.1-0-dev, libssl-dev and libpcre3-dev is installed.

**Comment by Papafox** [comment]
liblua5.1-0-dev contains lua.h, so there must an INCLUDE path problem.  Looks like you need to tweak the Makefile be adding something like 
`INCDIRS = -I/usr/include/lua5.1/`

You need to make sure lua.h is located in /usr/include/lua5.1

**Comment by furx** [comment]
Unfortunately, I added the line to the Makefile but it made no difference. I still get the same error.

lua.h is located in /usr/include/lua.5.1/lua.h

**Comment by lefcha** [comment]
Try `make INCDIRS=-I/usr/include/lua5.1 LIBLUA=-llua5.1`.

**Comment by furx** [comment]
Yes, that did the trick. Thanks :)
