### ISSUE TITLE
Expose "dryrun" flag to user config

### ISSUE THREAD

**Issue by djl** [lefcha/imapfilter#196]
Apologies if this already exists and I've just missed it.

In my config I have some rules that communicate with an external service (e.g. hit an HTTP endpoint). This can be potentially destructive and isn't something I'd like to do when performing a dry run.

Is there a way to get the status of the `-n` flag from my config? If not, would you be open to a feature request (or patch) that implements this?

**Comment by lefcha** [comment]
Closed by https://github.com/lefcha/imapfilter/commit/d45bea53e7cdb33130f42576b1c6773aff0396bc.

**Comment by lefcha** [comment]
You can access the dry-run mode from inside the config with `options.dryrun` which can be `true` or `false`.
