### ISSUE TITLE
error in logfile

### ISSUE THREAD

**Issue by dominikpflegerl** [lefcha/imapfilter#198]
I am trying to get imapfilter working on my debian VPS, but it's not working as it should.

Here's my config:

`options.timeout = 120`
`options.subscribe = true`
`business = IMAP {`
`    server = '',`
`    username = '',`
`    password = '',`}
`mailboxes, folders = business:list_all()`
`mailboxes, folders = business:list_subscribed()`
`business.INBOX:check_status()`
`function mail()`
`messages_case1 = business["INBOX"]:contain_from("case@case.com")`
`messages_case1:mark_seen()`
`messages_case11:move_messages(business["case"])`
`messages_case2 = business["INBOX"]:contain_subject("case")`
`messages_case2:mark_seen()`
`messages_case2:move_messages(business["FOLDER"])`
`messages_case3 = business["FOLDER"]`
`messages_case3:mark_seen()`
`end`
`become_daemon(2, mail)`

Here's the log file:

`Sun Aug 18 11:35:53 2019: /root/.imapfilter/config.lua:45: required argument left out
stack traceback:`
`[C]: in function 'error'`
`        /usr/local/share/imapfilter/common.lua:12: in function '_check_required'`
`        /usr/local/share/imapfilter/mailbox.lua:618: in function 'mark_seen'`
`        /root/.imapfilter/config.lua:45: in function 'commands'`
`        /usr/local/share/imapfilter/auxiliary.lua:70: in function 'become_daemon'`
`        /root/.imapfilter/config.lua:51: in main chunk`

mark_seen and become_daemon do not work, I already got an error while making imapfilter, but could solve it by adding `make INCDIRS=-I/usr/include/lua5.1 LIBLUA=-llua5.1`

**Comment by lefcha** [comment]
Hm, that is strange.

First you better try to run this without `become_daemon()`, like this:

```
options.timeout = 120
options.subscribe = true
business = IMAP {
  server = '',
  username = '',
  password = ''
}
messages_case1 = business["INBOX"]:contain_from("case@case.com")
messages_case1:mark_seen()
```

Also run imapfilter with `imapfilter -d ~/debug.log`.  Can you check the `debug.log` file, and copy/paste here the parts where the `SEARCH` request is sent, and also the response from the server?

Otherwise you can just copy/paste the whole `debug.log` file in a [GitHub Gist](https://gist.github.com).
