### ISSUE TITLE
imapfilter fails to log in if password contains a double quote

### ISSUE THREAD

**Issue by kheops2713** [lefcha/imapfilter#199]
Hello, and thank you for this very useful piece of software!

I have an IMAP account for which the password contains a double quote (`"`). The server is running Dovecot.

I don't save my password in the configuration file, so I input it when `imapfilter` prompts me (I copy-paste it from a keepass entry).

`imapfilter` tries to log in and fails wih the following:

```
imapfilter: IMAP (3): 1001 BAD Invalid characters in atom
imapfilter: authentication of kheops@domain.tld failed.
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/usr/share/imapfilter/account.lua:99: in field '_login_user'
	/usr/share/imapfilter/account.lua:59: in global 'IMAP'
	/home/kheops/.imapfilter/config.lua:1: in main chunk
```

Eventually, I found out that it works successfully if I manually add a backslash before the double quote in the string I give to `imapfilter` password prompt.

Maybe this should either be added to the documentation (like in the backslash case), or the double quote should automatically be escaped? It also seems possible to use `AUTHENTICATE PLAIN` instead of `LOGIN`, as in that case the password seems to be base64-encoded which could solve all problems related to IMAP special characters (`curl` uses that method).

Thank you!

**Comment by lefcha** [comment]
I confirm the problem.  Can you try the latest version from git as it includes commit https://github.com/lefcha/imapfilter/commit/6a2e04851206a16abdcc7ae5a6e2854047f9a0a0 that should fix this bug.

**Comment by dngray** [comment]
I found I found I needed to use this function, I wrote:

```lua
-- Escapes problematic characters in passwords.
function sanitize_pwd(pwd)
    -- Chomp off newline character that is sucked in from Password Store.
    pwd = string.gsub(pwd, "\n", "")

    -- Escape backslash characters that exist in passwords. Need to escape the
    -- escape characters at each 'level' where the password string is used
    -- otherwise escape characters are lost.
    --
    -- The slashes are escaped first. If they were escaped later then
    -- characters escaped later would be escaped again.
    pwd = string.gsub(pwd, '%\\', '\\\\')

    -- Escape double quote characters that exist in passwords.
    pwd = string.gsub(pwd, '%"', '\\"')

    return pwd
end
```

I use it with [pass](https://www.passwordstore.org):

```lua
status, password1 = pipe_from('pass {{ pass }}')
```

```lua
local {{ host.serverName }} = IMAP {
        server = '{{ host.server }}',
        username = '{{ host.username }}',
        password = sanitize_pwd(password1),
        ssl = 'tls13'
}
```
