### ISSUE TITLE
error when compiling on centos 7.6 64bit

### ISSUE THREAD

**Issue by almoorthi** [lefcha/imapfilter#200]
getting make error like below all dependencies installed lua-devel-5.1.4-15.el7.x86_64, openssl-devel-1.0.2k-16.el7_6.1.x86_64
make
cd src && make all
make[1]: Entering directory `/tmp/imapfilter/src'
cc -o imapfilter   auth.o buffer.o cert.o core.o file.o imapfilter.o list.o log.o lua.o memory.o misc.o namespace.o pcre.o regexp.o request.o response.o session.o signal.o socket.o system.o -lm -ldl -llua -lpcre -lssl -lcrypto 
socket.o: In function `open_secure_connection':
socket.c:(.text+0xfd): undefined reference to `SSL_set_hostflags'
socket.c:(.text+0x10e): undefined reference to `SSL_set1_host'
collect2: error: ld returned 1 exit status
make[1]: *** [imapfilter] Error 1
make[1]: Leaving directory `/tmp/imapfilter/src'
make: *** [all] Error 2

**Comment by hiqua** [comment]
This should be fixed now, although compiling imapfilter with an old OpenSSL version means that there's not name validation, see also https://github.com/lefcha/imapfilter/commit/9a9c15accef52fb79431edd492ddba3217ed050e#r35885821

**Comment by lefcha** [comment]
@hiqua This problem has been addressed by https://github.com/lefcha/imapfilter/commit/047655605a333af3cba1be3a669bc3fb049c3199

@almoorthi There was a problem building with OpenSSL versions between 1.0.2 and 1.1.0, but it has been fixed a few days ago by https://github.com/lefcha/imapfilter/commit/ab485741ff8d3bc6cd85019536e613e5e5130ac4.

Let me know if you still have any issues.

**Comment by hiqua** [comment]
Thanks a lot @lefcha (and sorry for the late answer)! I think this is the right approach: distributions shipping imapfilter with an old version of OpenSSL can always manually build imapfilter, knowing that it will have a vulnerability, and at this point it's no longer the responsability of this repository.
