### ISSUE TITLE
contain_from fails to match correct messages

### ISSUE THREAD

**Issue by Dzordzu** [lefcha/imapfilter#203]
## Issue
**Type**: bug
**Impact**: anytime you filter messages using contain_from
**Description**: Basically, it works (somehow). But I get additional, unwanted messages being filtered.
**Is this any kind of joke**: NO. I wish it was

## Example test
Config
```
messages = inbox:contain_from("example@example.com")
messages:move_messages(mailbox["example"])
```

And filtered messages are from:
* `example@example.com`
* `youex@gmail.com`
* `russian-mafia@mail.ru`

## Workaround
1. Use contains from
2. Then use match from (filter can be the same)

Works for larger mailboxes

**Comment by dymn** [comment]
The same problem. But first time contain_from worked properly and match rules, next time no one messages match.

Config:
```
results = some_mail.Sent:contain_to("example@gmx.de") +
   some_mail.Sent:contain_to("example@mail.ru") +
   some_mail["Архив"]:contain_from("example@gmx.de") +
   some_mail["Архив"]:contain_from("example@mail.ru")
results:move_messages(some_mail['example'])
```

$ imapfilter -v

```
S (4): * OK Yandex IMAP4rev1 at iva5-60acf91091fa.qloud-c.yandex.net:143 ready to talk with ::ffff:128.74.108.141:38222, 2020-Jan-29 23:01:44, g1nd6e00cCg1
C (4): 1000 NOOP
S (4): 1000 OK NOOP Completed.
C (4): 1001 CAPABILITY
S (4): 1001 OK CAPABILITY Completed.
C (4): 1002 STARTTLS
S (4): 1002 OK STARTTLS completed.
C (4): 1003 CAPABILITY
S (4): 1003 OK CAPABILITY Completed.
C (4): 1004 LOGIN "some_mail" *
S (4): 1004 OK LOGIN Completed.
C (4): 1005 CAPABILITY
S (4): 1005 OK CAPABILITY Completed.
C (4): 1006 NAMESPACE
S (4): 1006 OK NAMESPACE Completed.
C (4): 1007 LIST "" "%"
S (4): 1007 OK LIST Completed.
C (4): 1008 SELECT "Sent"
S (4): 1008 OK [READ-WRITE] SELECT Completed.
C (4): 1009 UID SEARCH CHARSET "UTF-8" ALL TO "example@gmx.de"
S (4): 1009 OK UID SEARCH Completed.
C (4): 100A UID SEARCH CHARSET "UTF-8" ALL TO "example@mail.ru"
S (4): 100A OK UID SEARCH Completed.
C (4): 100B SELECT "&BBAEQARFBDgEMg-"
S (4): 100B OK [READ-WRITE] SELECT Completed.
C (4): 100C UID SEARCH CHARSET "UTF-8" ALL FROM "example@gmx.de"
S (4): 100C OK UID SEARCH Completed.
C (4): 100D UID SEARCH CHARSET "UTF-8" ALL FROM "example@mail.ru"
S (4): 100D OK UID SEARCH Completed.
C (4): 100E LOGOUT
```
However, I know that there are messages in the folders that correspond to the selection rules. But imapfilter does not want to filter them out.
I am replacing @ with * in email - the rule is triggered for the first time. In the future, it does not work again.

**Comment by lefcha** [comment]
Unfortunately there's nothing imapfilter can do if the IMAP server has a broken implementation of the IMAP `SEARCH` command, which the `contain_*()` functions use.  Do you maybe know which server this is?

The only workaround is the one you mention to use the `match_*()` functions, preferably after you have narrowed down the results.
