### ISSUE TITLE
Exit status upon certificate errors

### ISSUE THREAD

**Issue by henkkakay** [lefcha/imapfilter#205]
It would be very nice to have a way to pick up any certificate issues (exit status codes) so the condition can be raised to the user/administrator.

Then user/administrator can then build whatever logic around it that fits them.

I dont want to turn off certificate checking (as per https://github.com/lefcha/imapfilter/issues/35 ) for the security risks.

Thanks!

**Comment by lefcha** [comment]
How do you mean? The exit code of the whole config to somehow pass if the problem was a certificate check, instead of a generic `ERROR_CONFIG` which is basically `2`?

**Comment by henkkakay** [comment]
Ah - so it already does it. Is there a listing of error/exit codes?

**Comment by lefcha** [comment]
It's quite limited at the moment, but I can look into making it more precise:

https://github.com/lefcha/imapfilter/blob/cc5a6480586f514b4faffe26c16a93f9569f2f68/src/imapfilter.h#L17-L22

**Comment by henkkakay** [comment]
Thank you @lefcha - this is great I guess code 5 is what I am looking for (when server side changes certificate I want to be notified)

**Comment by henkkakay** [comment]
wrote a quick script - below is the execution in interactive mode, so when certificate doesnt match it returns value of 2. So the code currently considers a rejection of certificate to be ERROR_CONFIG. So when is it ERROR_CERTIFICATE?

```
Server certificate subject: /OU=Domain Control Validated/OU=EssentialSSL Wildcard/CN=*.blahblah.com
Server certificate issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
Server key fingerprint: FE:FE:FE:FE:FE:FE:FE:FE:FE:FE:FE:FE:FE:FE:FE:FE
(R)eject, accept (t)emporarily or accept (p)ermanently? r
imapfilter: login request to user@domain@blahblah.com failed
**Command exited with two**
```

**Comment by lefcha** [comment]
I will need to improve this, and return `ERROR_CERTIFICATE` in all scenarios where the problem is the certificate checking.  It seems that some errors happen when the config is read and `ERROR_CONFIG` is returned.

**Comment by henkkakay** [comment]
Nice - thanks!
I can set my own script to look out for both ERROR_CONFIG and ERROR_CERTIFICATE - so the current situation is quite ok for me.

**Comment by lefcha** [comment]
With the latest version from git and specifically commit https://github.com/lefcha/imapfilter/commit/b46d9aea4043e8fa04223a03f9503fcff949fa6e, you should get `ERROR_CERTIFICATE` as the return value of imapfilter, if the problem was that `certificate verify failed`, which is the case if the SSL CA TrustStore of the system, or the one supplied, cannot verify the certificate.
