### ISSUE TITLE
Forward in-line attachments

### ISSUE THREAD

**Issue by bonelifer** [lefcha/imapfilter#207]
Is there a way to forward an email based on subject(contains) and email address as inline attachment so images show up to the person who gets forwarded to, but not mark mail as read so the main account also downloads the email.

**Comment by lefcha** [comment]
It's possible to filter mail based on subject and email address, and it's possible to leave mail unread for other mail clients to pick up, or mark messages as unread if they have been somehow marked read.

And if you have access to the IMAP account where you want to forward the messages to (ie. you own that account and have the username/password), then imapfilter can copy messages to that account, basically by creating exact duplicates on the destination account.

But forwarding email is not something imapfilter can do unless it uses an external mail client that utilizes the SMTP protocol, and then the `pipe_to()` command to pass the email content to that mail client.  For example a popular small mail client is [msmtp](https://marlam.de/msmtp/).
