### ISSUE TITLE
multi factor authentication

### ISSUE THREAD

**Issue by crotoc** [lefcha/imapfilter#212]
Thanks for your great software. It brings so much convenience to me!

I encountered a problem that our work email of Vanderbilt University enforce multifactor authentication. When login, it needs us to login our working account through DUO app. Is it possible to use imapfilter in this situation. Please let me know. Thanks very much!

**Comment by lefcha** [comment]
Do you have more details on how this works?

**Comment by scottkosty** [comment]
@crotoc Bumping in case you didn't see the above question.

**Comment by crotoc** [comment]
Sorry for the late reply and thanks for your bumping @scoggkosfy. The MFA used by our university is DUO. When I need to log it to a new app, it will ask me to fill in a code which is generated from DUO. We don't have access to choose app specific password that is usually an alternative way for MFA because Vanderbilt disable this kind of function. What kind of extra info do you need about my case. Thanks~

**Comment by lefcha** [comment]
For IMAP clients usually such services make it possible to use another password, that is generated just for the occasion, and it is strong enough.  I would check whether this is possible in your case.

AFAIK, IMAP doesn't support any kind of 2FA,  so I doubt that if your service provides an IMAP interface, it makes it mandatory to use DUO, too.  I would guess that if they provided IMAP access, they make it through special generated passwords, or OAuth, or some other alternative.

**Comment by crotoc** [comment]
Got you! I think you are right. Maybe I have no easy way to use imapfilter anyway. What a bad idea for them to make it impossible... Thanks anyway! Appreciate your efforts to create a such great tool!
