### ISSUE TITLE
Cannot compile on Alpine Linux v3.12.0

### ISSUE THREAD

**Issue by simbelmas** [lefcha/imapfilter#214]
## Issue

When trying to run `make all` on alpine 3.12.0 with pcre2 installed, the build fails with following error:
`/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lpcre`

## Installed Packages
* pcre2: pcre2-10.35-r0 x86_64
* pcre2-dev: pcre2-dev-10.35-r0
* imapfilter 276fcee815ece606053180fcfc40f6c47da5a551

## Troubleshoot
When running `pcre2-config` on alpine, we can find that library name should be `pcre2-8`

if the environment is overriden with `-e LIBPCRE='-lpcre2-8'` the build is successful.

The following Dockerfile is used to compile for x86/armv7: https://github.com/simbelmas/dockerfiles/blob/latest/imapfilter/Dockerfile

**Comment by lefcha** [comment]
Yes, I forgot to update the Makefile, and I did that earlier today: https://github.com/lefcha/imapfilter/commit/a17687c96b5a7844bb612063265fbf6de4a14ab9

**Comment by simbelmas** [comment]
I tested with new Makefile and it does not work because lua5.4 is not shipped with alpine. LUA 5.3 is the most recent one.
When overriding LIBLUA var and using the old value it works.
I overridden the value with `make -e LIBLUA='-llua'`

**Comment by lefcha** [comment]
I'll revert to the previous way of building to keep it simpler, and distribution agnostic: https://github.com/lefcha/imapfilter/commit/7025ecbfae95b5fadaed506c6d5fd635b3a9483f

**Comment by simbelmas** [comment]
The build succeeds without any override.
Many thanks :+1: 
I think we can close the issue.
