### ISSUE TITLE
internet-based realtime blacklist at an raspberry pi

### ISSUE THREAD

**Issue by Maagi93** [lefcha/imapfilter#217]
Hello together,

I use imapfilter on a raspberry pi and I want to use internet-based realtime blacklist.

How can I set up the utility bayesian-spam-filter at my raspberry pi? If I try to use the code below I get an error :/.

`all = myaccount.mymailbox:select_all()

results = Set {}
for _, mesg in ipairs(all) do
    mbox, uid = table.unpack(mesg)
    text = mbox[uid]:fetch_message()
    if (pipe_to('bayesian-spam-filter', text) == 1) then
        table.insert(results, mesg)
    end
end

results:delete_messages()
`

Thank you in advance!

**Comment by lefcha** [comment]
What error do you get?

**Comment by Maagi93** [comment]
I don´t know how to setup bayesian-spam-filter'. I need a tutorial or a documentation or sth. else? Or ist this the code I have to writhe in the config.lua?

`all = myaccount.mymailbox:select_all()

results = Set {}
for _, mesg in ipairs(all) do
mbox, uid = table.unpack(mesg)
text = mbox[uid]:fetch_message()
if (pipe_to('bayesian-spam-filter', text) == 1) then
table.insert(results, mesg)
end
end

results:delete_messages()

**Comment by Maagi93** [comment]
The Error I get:

imapfilter: /home/pi/.imapfilter/config.lua:974: required argument left out
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        /usr/share/imapfilter/common.lua:12: in function '_check_required'
        /usr/share/imapfilter/auxiliary.lua:27: in function 'pipe_to'
        /home/pi/.imapfilter/config.lua:974: in main chunk

**Comment by lefcha** [comment]
By `bayesian-spam-filter` I meant some command like utility that expects a some string as input, and will reply either positively or negatively whether the specified text is likely spam.  It's been years since I have used such a tool, but some that I remember using are Bogofilter, SpamAssassin, etc.

Now for the cause of the error, I would need to know what's on line `974` of your config file.  But from the looks of it, it seems that you only give 1 argument to `pipe_to()` while it expects 2 arguments.  Those arguments are the `command` to execute and the `data` to pass to that command, basically a string, some text.

**Comment by Maagi93** [comment]
line 974: "if (pipe_to(spamc, text) == 1) then"

how can i call spamassassin with pipe to correctly so i get a 0 or 1 back

**Comment by lefcha** [comment]
It seems that you might need to use `if (pipe_to('spamc -E', text) == 1 then`:

> -E
> Filter according to the other options, but set the process exitcode to 1 if message is spam, 0 if not spam or processing failure occurs. 

Ref: https://spamassassin.apache.org/full/3.1.x/doc/spamc.html

**Comment by sebastianludwig** [comment]
I've just recently set something like this up using bogofilter: https://procrastinative.ninja/2021/01/12/imapbogofilter/

P.S. @lefcha in the process I wrote a web UI for imapfilter: https://github.com/sebastianludwig/imapfilter-web-ui

**Comment by lefcha** [comment]
@sebastianludwig Thatnks, that's great work, both article and the web UI!

Feel free to add links to them from the imapfilter Wiki if you want: https://github.com/lefcha/imapfilter/wiki
