### ISSUE TITLE
Multiple accounts with same filters?

### ISSUE THREAD

**Issue by BlackScreen** [lefcha/imapfilter#222]
Hello,
I recently stumbled upon imapfilter while searching for a possibility to use a custom list of blacklisted adresses on my mail accounts. It works very well for me at the moment, but I have an idea which would help me, if possible, very much.
Is there a way to use the same set of rules and apply them to two (or more) accounts?
I saw an issue (https://github.com/lefcha/imapfilter/issues/88) where this was possible for multiple mailboxes, but maybe this works as well for multiple accounts.
Thanks for your help and for imapfilter!

**Comment by lefcha** [comment]
Yes, you can do that. you can write a function that takes a mailbox as an argument, and it applies the same filters on that mailbox.

You don't need to think in terms of accounts, because imapfilter works in terms of mailboxes.

Here's an example:

```lua
function myfilter(mbox, lists, news)
    mbox:contain_subject('ad').delete_messages()
    mbox:contain_from('list').move_messages(lists)
    if news then mbox:contain_subject('news').move_messages(news) end
end

account1 = IMAP { ... }
account2 = IMAP { ... }
account3 = IMAP { ... }

myfilter(account1.INBOX, account1.lists, account1.news)  -- Applies all filters
myfilter(account2.INBOX, account2.lists)  -- Skips filtering news
myfilter(account3.INBOX, account1.lists)  -- Moves lists from account3 to account1
```

**Comment by BlackScreen** [comment]
Perfect, thanks for this tip. It is working fine! :)
