### ISSUE TITLE
Compiling on macOS /w Homebrew

### ISSUE THREAD

**Issue by rjhornsby** [lefcha/imapfilter#223]
There might be another way, but I had to modify `src/Makefie` to get it to compile on macOS.

Need to install openssl and lua if not already present:

`$ brew install openssl lua`

update these lines in `imapfilter/src/Makefile`:

```
INCDIRS = -I/usr/local/include/lua -I/usr/local/Cellar/openssl@1.1/1.1.1j/include
LIBDIRS = -L/usr/local/Cellar/openssl@1.1/1.1.1j/lib
```

I'm not completely sure why there isn't a `/usr/local/include/openssl` - possibly to keep from colliding with the OS version. Not keen on pinning to a specific version like that, but it works for now.

**Comment by lefcha** [comment]
Thanks for the instructions. As I can't maintain up-to-date instructions on different platforms, I decided to just have a generic Makefile, that should make it obvious how to build, and also have a bunch of variables that users can override like you did above.

For example on my Debian, I build with: `make -j INCDIRS=-I/usr/include/lua5.3 LIBLUA=-llua5.3 LIBPCRE=-lpcre2-8`

But for this reason I have enabled the Wiki, and some people have already added build instructions, and other ideas: https://github.com/lefcha/imapfilter/wiki

Please feel free to add there these instructions.
