### ISSUE TITLE
Best way to make it traceable

### ISSUE THREAD

**Issue by opensource21** [lefcha/imapfilter#226]
I wonder if there exist any strategy to make the move traceable. So that we can understand why a mail is moved to a specific folder. I first thought that it would be a good idea to add a specific header, but therefore I must download each complete message. A real inefficient way.
But I wonder if there is an efficient way to log this, perhaps something like messageid and rulename?
Or exists a default functionality?

**Comment by lefcha** [comment]
Currently imapfilter only prints the count of messages that an action is applied to.

IIUC, you would like to have more detailed logging, with each message that matches a rule or is acted upon?

**Comment by opensource21** [comment]
Well I'm newbie and I thought about how I could analyse a situation where something wire happens. So my idea was to log the message-id and give each rule a specific id.

**Comment by lefcha** [comment]
You can print the mailbox names and message ids like this:

```lua
function print_uids(filter, messages)
    print('Filter "' .. filter .. '" matched messages:')
    for _, msg in ipairs(messages) do
        mbox, uid = unpack(msg)
        print('  ' ..mbox._string .. '/' .. uid)
    end

end

messages = myaccount.INBOX:is_new())
print_uids('myaccount.INBOX:is_new()', messages)
```

This is just an example, you can print this in a better way.  The output of this is something like:

```
Filter "myaccount.INBOX:is_new()" matched messages:
  myaccount@example.org/INBOX/75
  myaccount@example.org/INBOX/76
  myaccount@example.org/INBOX/77
```
