### ISSUE TITLE
Imrovement for enter_idle() example

### ISSUE THREAD

**Issue by opensource21** [lefcha/imapfilter#227]
I read [extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua). If the job which must be done need a some times like spam-filter, it could happen that mails arrive during processing first mails. These mails wouldn't process till another email arrive. I wrote a small function in util.lua.

Perhaps it's useful to put it into the extend.lua?

Thanks for your great work!

```
require("os")
-- Block until something happens, assuming server supports IMAP IDLE
-- Note: there is still a window between checking unseen messages
-- and entering idle where we could miss a new arrival.  In that
-- case it will have to wait until another email arrives.
-- It's possible to add a ping-mail which will be not delivered.
-- ping = folder:is_unseen() * folder:match_subject("^PING$") * folder:match_from(".*i@mydomain.com")
-- ping:mark_seen()
function waitForNew(folder)
    if #folder:is_unseen() == 0 then
        local update = folder:enter_idle()

        -- Sleep 5 minutes if IDLE isn't supported
        if update == false then
            os.execute("sleep " .. tonumber(300))
        end
    end
end
```

**Comment by lefcha** [comment]
Thanks, that's indeed an issue, I'll consider improving the example with IDLE.

Notice that imapfilter already includes a sleep function:

https://github.com/lefcha/imapfilter/blob/2bbc12962756699cad8882c1569de7bff6db9e15/src/auxiliary.lua#L75

And:

https://github.com/lefcha/imapfilter/blob/2bbc12962756699cad8882c1569de7bff6db9e15/src/system.c#L232-L237

So you should be able to do `sleep(300)` in your code, without a need for `os`.

Also, if you would like to add more useful code snippets, you can do that at the Wiki: https://github.com/lefcha/imapfilter/wiki

**Comment by lefcha** [comment]
Closed by https://github.com/lefcha/imapfilter/commit/871136031b0e15eba67ba92678cbd02f36057c78.
