### ISSUE TITLE
Missing braces in TRY() macro might lead to branch confusion & incorrect state management

### ISSUE THREAD

**Issue by hhoffstaette** [lefcha/imapfilter#235]
When building with gcc 11.2.0 I get lots of warnings in request.c:
```
request.c: In function 'request_noop':
request.c:57:19: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
   57 |                 } else                                                         \
      |                   ^~~~
request.c:155:9: note: in expansion of macro 'TRY'
  155 |         TRY(t = send_request(ssn, "NOOP"));
      |         ^~~
request.c:59:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
   59 |                         ssn = NULL;                                            \
      |                         ^~~
```

This is due to a lack of explicit block demarcation in the [else-branch](https://github.com/lefcha/imapfilter/blob/master/src/request.c#L57) before the return. While the formatting seems to indicate the _intended_ logic, it's not clear whether the else-block should cover only the consecutive two statements (closing before the `return -1`) or include it.
I _think_ the former is intended, otherwise the preceding top-level if would miss a return statement. Adding braces like this fixes the warning and looks better to me:
```
		} else {						       \
			session_destroy(ssn);				       \
			ssn = NULL;					       \
		}							       \
		return -1;						       \

```
But again I don't know if this was the intention - maybe this is the underlying reason for problems with #231?

**Comment by lefcha** [comment]
Closed by https://github.com/lefcha/imapfilter/commit/daef6161e4801bc0f8c6719d37c8392cc702e247.
