### ISSUE TITLE
2-Step Verification for gmail 

### ISSUE THREAD

**Issue by jchollingsworth** [lefcha/imapfilter#239]
Hi.. I recently noticed imapfilter was no longer doing it's job, and I realized it's because Gmail has automatically switched on 2-Step Verification (as of 9th Nov 2021)... which prevents imapfilter from working properly. Currently, it's possible to switch this option off in Gmail, but I think they will remove this in the future. Therefore, it would be great to find a way to manage this problem so that imapfilter continues to work with gmail.
Thanks, J

**Comment by NickHastings** [comment]
You should be able to use an app password for this. Go to https://myaccount.google.com/security Look for the "Signing in to Google" section.

**Comment by lefcha** [comment]
I think it should be possible to have an App Sassword, and thus bypass 2FA: https://support.google.com/mail/answer/185833?hl=en

Are any mail clients that can handle 2FA, apart from Gmail itself?

**Comment by PeterS242** [comment]
Honestly this could use a broader discussion.  Perhaps there is room for a LUA-enabled-but-not-necessarily-IMAP-or-IMAPS-limited application?  Looking at some of the other 'issues', abstracting the email-connection-type by one layer would allow you to access local disk, remote disk, databases, email servers, etc, using potentially the same tool.

I was impressed by how the Microsoft Azure CLI for Linux handles 2FA.  When you do an "az login" it tells you to "go to this specific URL in a browser."  This then steps you through the login process on the Azure side and ultimately grants you access.  Other possibilities could include a text prompt "enter the Authenticator code" ala Google Authenticator, or like a Duo login (https://duo.com/docs/loginduo) where you can select one of 3 different options: Duo Push to <phone number>, Phone call to <phone number>, SMS passcodes to <phone number>; etc.

**Comment by pdemaret** [comment]
I am pleased to confirm that the solution you provided here does work like a charm : activate 2FA, create an App password, update the lua config file. Thank you @lefcha @PeterS242 @jchollingsworth @NickHastings, great insight !

**Comment by pdemaret** [comment]
Hi hi-flyer, you just have to create an app password in your google account. The how-to reference is given in your message : https://support.google.com/accounts/answer/185833. Once created, you copy the password in the lua config file, where it replaces your old password. Nothing to do with a duo key.

**Comment by hi-flyer** [comment]
Thank you, I missed that step. It is now working.
Appreciate the help.
