### ISSUE TITLE
--quiet option?

### ISSUE THREAD

**Issue by mzagrabe** [lefcha/imapfilter#242]
Greetings!

Thank you for writing imapfilter.

I am a new user and am planning on using imapfilter via cron. I'd like to only be notified of serious errors from cron's email.

When I ran a test of imapfilter it was a little noisy:

$ imapfilter
1 messages moved from foo@example.com@imap.gmail.com/Ticket-Test to foo@example.com@imap.gmail.com/Ticketed.

I'd rather not redirect to /dev/null to suppress all the output. Is there a --quiet option? If not, would you consider implementing one?

Thanks!

**Comment by lefcha** [comment]
All these messages are printed from the Lua part, and they are controlled by `info` option (see `imapfilter_config(5)`).

So try setting `options.info = false` on the top of your config file.
