### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by HoffmannP** [lefcha/imapfilter#247]
On startup imapfilter issues an error saying
```
imapfilter: initiating SSL connection to imap.$domain.$tld; error:14090086:SSL
    routines:ssl3_get_server_certificate:certificate verify failed
```

I tried to debug the issue using 
```
openssl s_client -connect imap.$domain.$tld:993 -status
```
but this looked unsuspicious.

Any idea how I could proceed?

**Comment by lefcha** [comment]
What happens if you specify at the top of your config file `options.hostname = false`?
