### ISSUE TITLE
please update apt repo to last version

### ISSUE THREAD

**Issue by mybuntu-git2** [lefcha/imapfilter#248]
I installed via apt on ubuntu for arm64 this (**AWESOME**) package
at one point stumbled on 
` /usr/share/imapfilter/mailbox.lua:68: bad argument #2 to 'select' (string expected, got number)
`
and realised looking around that apt is 2.6.X not 2.7.X

can you update apt?
I cannot use docker, it uses "a lot" of memory and am on a Pi.

**Comment by mybuntu-git2** [comment]
sorry forgot to put details.
```
 apt list -a imapfilter
Listing... Done
imapfilter/focal,now 1:2.6.16-1 arm64 [installed]
```

**Comment by lefcha** [comment]
What version of Ubuntu are you using? Seems that the later versions have an up-to-date imapfilter: https://packages.ubuntu.com/search?keywords=imapfilter&searchon=names&suite=all&section=all

Possibly you can just grab the latest package for arm64 and install it: https://packages.ubuntu.com/jammy/arm64/imapfilter/download

Also note that it's not hard to build imapfilter from the source code.

**Comment by mybuntu-git2** [comment]
I run imapfilter on 20.04 on an odroid N2+, but thanks I will build from source
