### ISSUE TITLE
lua-hashings not working with imapfilter

### ISSUE THREAD

**Issue by hi-flyer** [lefcha/imapfilter#250]
Imapflter 2.6.16 is making lua calls for version 5.2 functions but need it to call lua 5.3
I am using ubuntu 20.04 with lua version 5.3.5 
I installed Lua-hashings using luarocks which requires lua version 5.3.
if I run the lua interperter and the command hs = require("hashings").sha256()
it works fine as the test below shows
lua 
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> hs = require("hashings").sha256()
> hs:update("test")
> print ("\t\tupdating subjectmovehash with",hs:hexdigest().."\n")
		updating subjectmovehash with	9F86D081884C7D659A2FEAA0C55AD015A3BF4F1B2B0B822CD15D6C15B0F00A08

> 

but if I run imapfilter with the command hs = require("hashings").sha256() it fails with the following msg 
module 'hashings' not found:
	no field package.preload['hashings']
	no file '/usr/local/share/lua/5.2/hashings.lua'
	no file '/usr/local/share/lua/5.2/hashings/init.lua'
	no file '/usr/local/lib/lua/5.2/hashings.lua'
	no file '/usr/local/lib/lua/5.2/hashings/init.lua'
	no file '/usr/share/lua/5.2/hashings.lua'
	no file '/usr/share/lua/5.2/hashings/init.lua'
	no file './hashings.lua'
	no file '/usr/local/lib/lua/5.2/hashings.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/hashings.so'
	no file '/usr/lib/lua/5.2/hashings.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './hashings.so'

tried copying /usr/local/share/lua/5.3 in to /usr/local/share/lua/5.2 and it failed (I guess as it though it was 5.2 code) with the following
error loading module 'hashings.adler32' from file '/usr/local/share/lua/5.2/hashings/adler32.lua':
	/usr/local/share/lua/5.2/hashings/adler32.lua:73: unexpected symbol near '<'
stack traceback:
	[C]: in ?
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/lua/5.2/hashings/init.lua:23: in main chunk
	[C]: in function 'require'
	/home/xxxx/.imapfilter/config.lua:636: in function 'configuredatafn'
	/home/xxxx/.imapfilter/config.lua:1144: in main chunk

hashings used to work on my old server when running imapfilter but when I transitioned, something got lost.

can you give me a hint how to make imapfilter make use 5.3
thanks

**Comment by hi-flyer** [comment]
followup: have found on my laptop using ubuntu 20.04 desktop the require works correctly but on my server using ubuntu 20.04 server, the require fails as shown above.

**Comment by lefcha** [comment]
Well if imapfilter on that system is compiled using Lua 5.2, it will probably not be possible to load a module that is using Lua 5.3.

Your best bet is to re-compile imapfilter yourself, using the source code, and whatever version of Lua you want (5.1-5.4 are supported).

**Comment by hi-flyer** [comment]
after updating Ubuntu to 22.04, I had to compile imapfilter to get to version 2.7.6. To compile it I had to modify the src/Makefile line LIBLUA = -llua to LIBLUA = -llua5.3 to make it compile version 2.7.6 as apt installed version of imapfilter is 2.6.15 (at least on my system)

hope this is helpful for someone else
PS thanks for a great application.
