### ISSUE TITLE
Segfault when using `options.recover` and re-login fails or password was changed

### ISSUE THREAD

**Issue by rhaas80** [lefcha/imapfilter#254]
imapfilter can fail with a segfault if one uses `options.recover = true` and the login fails or if one has changed the password in the lua account object in between initial login and the recover operation.

Pull request #253 has details.

A reproducers is something like this:

```lua
account = IMAP {
   server = 'outlook.office365.com',
   username = 'you@example.com',
   password = "secretsecret"
}

print("re-login")
account:logout()
account:login()

print("logout and login")
account:logout()
account._account.password = "foobar"
account:login()
```

**Comment by lefcha** [comment]
Thanks again for reporting, closed by f48fb06adc23315d1e437f5416cf7acde59b7779 as mentioned in https://github.com/lefcha/imapfilter/pull/253
