### ISSUE TITLE
Imapfilter -V wrong version Ubuntu 22.04

### ISSUE THREAD

**Issue by mybuntu-git2** [lefcha/imapfilter#263]
Under Ubuntu 22.04 arm64, 
`Sudo apt install —reinstall imapfilter `
Does the job:
`Setting up imapfilter (1:2.7.5-1build1) ...
Processing triggers for man-db (2.10.2-1) ... `
But then,
 imapfilter -V
Returns
`IMAPFilter 2.6.15  Copyright (c) 2001-2019 Eleftherios Chatzimparmpas `

**Comment by hhoffstaette** [comment]
Looks like a packaging problem; imapfilter built from source reports the correct version.

**Comment by lefcha** [comment]
I was wondering whether I might have forgotten to update the version in the code (the one that `-V` reports) in version 2.7.5, but that's not the case, as can be seen here: https://github.com/lefcha/imapfilter/blob/2bbc12962756699cad8882c1569de7bff6db9e15/src/version.h

So it must be a packaging problem as mentioned.
