### ISSUE TITLE
ssl cert check

### ISSUE THREAD

**Issue by ktpx** [lefcha/imapfilter#267]
Is it possible to disable verification of certs?  I need to access IMAP via an ssh tunnel with forwarded port.   Ill assume the prog then tries to 
authenticate "localhost"  ..and it fails.

Thanks,

**Comment by lefcha** [comment]
Try setting `options.certificates = true` in your config file.

**Comment by lefcha** [comment]
> Im assuming thats a global setting, as it fails to parse in the IMAP setting

Yes, that's right.

> But it does not make any difference, still same err.

Oh, probably it's the server hostname validation then. Try `options.hostnames = true`.

**Comment by ktpx** [comment]
> Also just realized that I had a mistake in the initial option, it should be: `options.certificates = false`, ie. not `true`.
> 
> So try disabling one or the other option, and then try disabling both.

Ah yes, certificates = false makes sense :D Great, that worked, didn't need the other option for this case.

Thank you!

**Comment by ktpx** [comment]
Closing.
