### ISSUE TITLE
error:0A000086:SSL routines::certificate verify failed

### ISSUE THREAD

**Issue by m99coder** [lefcha/imapfilter#274]
I updated `imapfilter` to version 2.8.1 which depends on [OpenSSL 3](https://github.com/Homebrew/homebrew-core/blob/a416fc1102fb3db3d474dc60b1e1624cf0789321/Formula/i/imapfilter.rb#L21).

```shell
→ imapfilter -V
IMAPFilter 2.8.1  Copyright (c) 2001-2023 Eleftherios Chatzimparmpas

→ openssl version
OpenSSL 3.1.3 19 Sep 2023 (Library: OpenSSL 3.1.3 19 Sep 2023)

→ imapfilter
S (6): * OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN STARTTLS LOGINDISABLED] IMAP server ready H migmx103 27.4 IMAP-1N6tr5-1rYj8V0soB-017c60
C (6): 1000 CAPABILITY
S (6): 1000 OK CAPABILITY completed
C (6): 1001 STARTTLS
S (6): 1001 OK Begin TLS negotiation now
imapfilter: initiating SSL connection to imap.gmx.net; error:0A000086:SSL routines::certificate verify failed
```

Is there anything I can do to fix that?

All the best,
Marco

**Comment by m99coder** [comment]
This works. I just read that it’s not recommended.

**Comment by lefcha** [comment]
Yes, this is explained in [RFC2818#section-3.1](https://datatracker.ietf.org/doc/html/rfc2818#section-3.1), and it basically happens because the server certificate server name doesn't match the hostname where imapfilter tries to connect to.

We can verify what the DNS names that certificate has with a command like this:

```sh
$ openssl s_client -connect imap.gmx.de:993 </dev/null 2>/dev/null | openssl x509 -noout -ext subjectAltName 
X509v3 Subject Alternative Name: 
    DNS:mail.gmx.net, DNS:mail.gmx.de, DNS:smtp.gmx.net, DNS:smtp.gmx.de, DNS:imap.gmx.net, DNS:imap.gmx.de, DNS:pop.gmx.net, DNS:pop.gmx.de
```

What are you using as a hostname in your imapfilter's configuration file?

**Comment by m99coder** [comment]
So far, I have not used a `hostname` config setting for the account. I changed it like this:

```lua
account = IMAP {
    server = 'imap.gmx.net',
    hostname = 'imap.gmx.net',
    username = 'user@gmx.de',
    password = 'Password',
}
```

But still without `options.hostnames = false`, the SSL certificate verification fails.

**Comment by lefcha** [comment]
This is weird because for me TLS negotiation works fine on this server. With this config:

```lua
account = IMAP {
    server = 'imap.gmx.net',
    username = 'user@gmx.de',
    password = 'password',
}
account.INBOX:check_status()
```

Then:

```sh
$ imapfilter -v
S (3): * OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN STARTTLS LOGINDISABLED] IMAP server ready H migmx007 27.4 IMAP-1M59nC-1qx1it1DK0-000JFb
C (3): 1000 CAPABILITY
S (3): 1000 OK CAPABILITY completed
C (3): 1001 STARTTLS
S (3): 1001 OK Begin TLS negotiation now
C (3): 1002 CAPABILITY
S (3): 1002 OK CAPABILITY completed
C (3): LOGIN * *
S (3): 1003 NO authentication failed
```

So it succeeds with `OK Begin TLS negotiation now`, and then naturally it fails during authentication.

What fingerprint do you get when you do the following?

```
$ openssl s_client -connect imap.gmx.net:993 2>/dev/null | openssl x509 -fingerprint -noout
SHA1 Fingerprint=BF:A5:40:61:C3:13:A2:95:88:73:C9:9A:DE:A0:C8:85:7B:5E:C3:61
```

**Comment by m99coder** [comment]
Strangely, I get a different fingerprint. Any idea, how this can happen?

```shell
→ openssl s_client -connect imap.gmx.net:993 2>/dev/null | openssl x509 -fingerprint -noout
SHA1 Fingerprint=F6:27:3A:15:3A:EC:D3:C8:38:E2:4B:05:F5:A4:F3:E7:28:E4:8E:2E
```

**Comment by m99coder** [comment]
I found the issue: [AVG AntiVirus](https://www.avg.com/en-gb/avg-antivirus-for-mac#mac) put itself into the chain. I uninstalled it and now `imapfilter` is working again as before.
