### ISSUE TITLE
Compilation on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by dewi-ny-je** [lefcha/imapfilter#281]
```
make[1]: Entering directory '/home/olaf/src/imapfilter/src'
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"' -DCONFIG_SSL_CAPATH='"/etc/ssl/certs"' -DCONFIG_SSL_CAFILE='"/etc/ssl/cert.pem"'   -c -o buffer.o buffer.c
In file included from buffer.c:3:
imapfilter.h:9:10: fatal error: lua.h: No such file or directory
    9 | #include <lua.h>
      |          ^~~~~~~
```

and so on. It can be solved by adding in src/Makefile 
`INCDIRS = -I/usr/include/lua5.4`

The same for -llua
`/usr/bin/ld: cannot find -llua: No such file or directory`
which is solved by changing -lua to -lua5.4 (in my case).

Maybe some preconfiguration should take place before Makefile starts, or the instructions should mention these adaptations, so that people less used to compilation won't spend 20 minutes looking for a solution.

**Comment by lefcha** [comment]
There are some instructions in the Wiki for a few years now: https://github.com/lefcha/imapfilter/wiki/Compiling-on-Ubuntu

I wanted to keep the config/build simple, and don't go after what each distribution decides to do.

Normally, when one installs Lua it should end up in the standard library/include path, and thus imapfilter should build fine with that. But some distributions like Debian/Ubuntu seem to place Lua dev files in special directories causing this issue.

Still the Makefile is intentionally very simple, so it's very easy to configure the paths by setting some variables.
