### ISSUE TITLE
Update docs: extended.lua (password example)

### ISSUE THREAD

**Issue by TimmFitschen** [lefcha/imapfilter#284]
https://github.com/lefcha/imapfilter/blob/9e6661278572009a92a8e125c9b339232a9735a1/samples/extend.lua#L128

I have a setup where I store the password for my imap account in a [password store](https://www.passwordstore.org/). I noticed that the string returned by pass has a trailing line break, so I needed to change the referenced line to

```lua
password = password:gsub('[\n\r]', '')
```

I think this should be updated in the extended.lua file, especially for users who are not familiar with lua (as am I, it took me a while to figure out whats wrong).

That being said, if there is any idiomatic lua way to do this, please add that instead and teach me ;)

**Comment by lefcha** [comment]
Good point, fixed it: https://github.com/lefcha/imapfilter/commit/2665c776331b4e7482a997bbe48706e2806e3cd8
