### ISSUE TITLE
Connection issues after updating to 2.8.2

### ISSUE THREAD

**Issue by vaygr** [lefcha/imapfilter#291]
I recently updated imapfilter to 2.8.2 and started experiencing connection issues, but the log stays clear.

How I found out: I have this line to get the password in my config file:

```lua

status, password = pipe_from('gpg --batch -q --decrypt ~/.config/mutt/mail.gpg')

```

And after upgrading to 2.8.2 the password is prompted randomly from every few minutes to every several hours. This typically happens when connection is interrupted or switching between VPNs.

I use the user systemd service:

```ini
[Unit]
Description=Imapfilter Mail Filter
Documentation="man:imapfilter(1)" "man:imapfilter_config(5)"
ConditionPathExists=%h/.imapfilter/config.lua

[Service]
Type=simple
ExecStart=/usr/bin/imapfilter -c %h/.imapfilter/config.lua
RestartSec=60
Restart=on-failure

[Install]
WantedBy=default.target
```

and I'm prompted with the password only on user session startup once.

There are no issues with the gpg-agent. Downgrading to 2.8.1 solves the problem.

It seems there are only 3 commits in `2.8.1..2.8.2`, so not sure which one could be the culprit.

**Comment by lefcha** [comment]
Hm, that is strange as there weren't any changes to networking between these 2 versions: https://github.com/lefcha/imapfilter/compare/v2.8.1...v2.8.2

Can you reproduce with a small config that you can share? Also can you produce a debug file with `-d debug.log` and share it?

**Comment by vaygr** [comment]
Thanks, I'm curious if it could be due to other package updates in the system that only imapfilter can trigger. I've followed advice in https://github.com/lefcha/imapfilter/issues/231#issuecomment-2041016351 and will try to reproduce in the coming weeks.

**Comment by vaygr** [comment]
Quick update here: so I found the root cause, and it's actually another process that's invoking `gpg` very randomly.
