### ISSUE TITLE
filtering against ms exchange imap server not working

### ISSUE THREAD

**Issue by jjYBdx4IL** [lefcha/imapfilter#33]
Example mail header line:

From: Some Name &lt;noreply@some.domain&gt;

contain_from('@some.domain') does not match such mails. In general, contain_from and contain_to never match the mail address part between the <>'s.

**Comment by PeterS242** [comment]
@jjYBdx4IL , it has been my experience that you can in fact use the domain in the contain_*() queries, but only like this:

contain_from('some.domain')
contain_to('another.domain.edu')
contain_cc('test.domain')

Once you have that set of messages you can then use the match__() methods as described above to get the more specific emails.
