### ISSUE TITLE
imapfilter.c:(.text+0x23c): undefined reference to `TLSv1_1_client_method' compile error

### ISSUE THREAD

**Issue by cristiroma** [lefcha/imapfilter#63]
When compiling the package on CentOS 6.2 I get this error. 
I have tried to use -lssl="/var/local/openssl-0.9.8y/" without success.

Environment

cat /etc/redhat-release 
CentOS release 6.2 (Final)

Installed Packages
Name        : openssl
Arch        : x86_64
Version     : 1.0.0
Release     : 27.el6_4.2
Size        : 3.6 M
Repo        : installed
From repo   : updates
Summary     : A general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.

cd src && make all
make[1]: Entering directory `/home/cristiroma/imapfilter/src'
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o auth.o auth.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o buffer.o buffer.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o cert.o cert.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o core.o core.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o file.o file.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o imapfilter.o imapfilter.c
imapfilter.c: In function ‘main’:
imapfilter.c:107: warning: implicit declaration of function ‘TLSv1_1_client_method’
imapfilter.c:107: warning: passing argument 1 of ‘SSL_CTX_new’ makes pointer from integer without a cast
/usr/include/openssl/ssl.h:1457: note: expected ‘const struct SSL_METHOD *’ but argument is of type ‘int’
imapfilter.c:108: warning: implicit declaration of function ‘TLSv1_2_client_method’
imapfilter.c:108: warning: passing argument 1 of ‘SSL_CTX_new’ makes pointer from integer without a cast
/usr/include/openssl/ssl.h:1457: note: expected ‘const struct SSL_METHOD *’ but argument is of type ‘int’
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o list.o list.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o log.o log.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o lua.o lua.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o memory.o memory.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o misc.o misc.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o namespace.o namespace.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o pcre.o pcre.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o regexp.o regexp.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o request.o request.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o response.o response.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o session.o session.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o signal.o signal.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o socket.o socket.c
cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/local/share/imapfilter"'     -c -o system.o system.c
cc -o imapfilter   auth.o buffer.o cert.o core.o file.o imapfilter.o list.o log.o lua.o memory.o misc.o namespace.o pcre.o regexp.o request.o response.o session.o signal.o socket.o system.o -lm -llua -lpcre -lssl -lcrypto 
imapfilter.o: In function`main':
imapfilter.c:(.text+0x23c): undefined reference to `TLSv1_1_client_method'
imapfilter.c:(.text+0x255): undefined reference to`TLSv1_2_client_method'
collect2: ld returned 1 exit status
make[1]: **\* [imapfilter] Error 1
make[1]: Leaving directory `/home/cristiroma/imapfilter/src'
make: **\* [all] Error 2

**Comment by JohnsonFromChina** [comment]
suse 11sp3, how to update openssl and libopenssl-devel,many packages depend on  the old openssl ? i almost failed for 2 month

**Comment by lefcha** [comment]
Which version of OpenSSL does SuSE 11 SP3 come with, 0.9.8j? Isn't it possible to build imapfilter with that?

**Comment by JohnsonFromChina** [comment]
yes,it's 0.9.8j,original version of sles suse 11 sp3
