### ISSUE TITLE
inconsistent return values

### ISSUE THREAD

**Issue by tezeb** [lefcha/imapfilter#82]
Multiple functions has inconsistent return statements ie. mailbox.check_status shall return 4 int values, but in certain cases it returns false or even nothing at all. More examples may be found by searching mailbox.lua.

Although I am not really familiar with lua, I can propose pull with fixes, but I would like to know what is correct solution for this problem. Especially in case of Mailbox.check_status it is quite complicated, as returning 0,0,0,0 may be treated both as an error and as valid empty inbox.

It might be necessary to change signature of this function to return bool,int,int,int,int  to be able to handle such case.

**Comment by lefcha** [comment]
Closed by f11de211cbb627a353e7eb7f53b2e04c05edfcea.

**Comment by tezeb** [comment]
Thanks for this fix :)
