### ISSUE TITLE
Searching entire account

### ISSUE THREAD

**Issue by muchweb** [lefcha/imapfilter#86]
What is the most efficient way to search messages in all mailboxes for a given account?

The most obvious would be to use `list_all` and then loop through results. But I suspect that this will perform many requests, making it very slow.

**Comment by lefcha** [comment]
If you want to search everything in an account, without knowing the structure or without being more specific by choosing a few mailboxes, then yes, this would be possible by using `list_all` (or `list_subscribed` if you don't care for non-subscribed mailboxes).

The IMAP protocol does not support this, but it seems there's an extension called [RFC 6237 - IMAP4 Multimailbox SEARCH Extension](http://tools.ietf.org/search/rfc6237), which seems to do this.  I haven't worked with it (in fact I didn't know about it 5 minutes ago) and thus imapfilter doesn't support this extension.

But I'm also not sure if IMAP servers nowadays support this so called `MULTISEARCH` capability. I suggest that you check with your server by executing imapfilter with the `-d debug.out` option, and then look for the `MULTISEARCH` string in the output file, and specifically in the `CAPABILITY` response the server sent.

It would be interesting to support this extension if it is widely used today...
