### ISSUE TITLE
Best way to run same filters on multiple folders

### ISSUE THREAD

**Issue by mathomp4** [lefcha/imapfilter#88]
Imapfilter gurus:

This might be a FAQ but my Lua skills are pretty low (I'm a Fortran programmer, mainly), so I'm hoping someone here can help me out. I have quite a few imapfilter rules that help sort all my mail but they all operate on INBOX. I was wondering how could I go about applying all the filters to more than one folder. That is, also move any messages matching the filters that are in "Sent Messages" or whatever imapfilter calls my Sent folder. That way all my message threads are "complete".

Obviously, I could duplicate the rules...but that's a bit brute force even for me. Rather, I was wondering if there is a way in Lua to go from:
```
wrf = account['INBOX']:contain_subject('Wrf-news')
account['INBOX']:move_messages(account['WRF'],wrf)
```
to:
```
wrf = account.mailboxes:contain_subject('Wrf-news')
account.mailboxes:move_messages(account['WRF'],wrf)
```
where mailboxes is an array/list/hash/whatever.

**Comment by lefcha** [comment]
If you want to repeat the same for a few mailboxes you want to specify, you can do like this:

```lua
mailboxes = { 'INBOX', 'Foo', 'Bar' }
for _, mbox in ipairs(mailboxes) do
    wrf = account[mbox]:contain_subject('Wrf-news')
    wrf:move_messages(account['WRF'])
end
```

In the Lua table `mailboxes` you include all mailboxes you want to apply this action to.

**Comment by mathomp4** [comment]
@lefcha Hmm. Okay, I'll give that a shot! 

I guess that's sort of like "for key, value in dict" in Python, eh? Is the "_" some special Lua variable like "$_" in Perl? (As you can my Lua programming skills are "copy-and-paste from imapfilter posts and pray it does what I want. I'm trying to learn, though!)

**Comment by lahwaacz** [comment]
The "_" variable is a "dummy variable", which is frequently used when its value is not important for the code. Otherwise it behaves like a regular variable. You can see it in Python too, but there it has also other uses -- see e.g. http://stackoverflow.com/a/5893946/4180822

**Comment by mathomp4** [comment]
Huh. A built-in dummy variable. Cool. I never knew about it in Python, but looking at that link, I'm glad I didn't. It has enough use cases besides "dummy" that I know I would be spending a week debugging some script before figuring out it was the @#$#@ing underscore. :)
