### ISSUE TITLE
imapfilter failing on OSX - not sure why

### ISSUE THREAD

**Issue by maxandersen** [lefcha/imapfilter#90]
Hi, 

I've used imapfilter for years now. Worked like a charm. 

I normally run it on a Linux box but from time to time I run it from osx too.

Today was one of those times and today it stopped working.

```
Enter password for mail.corp.com:
Trying to login...
imapfilter: login request to max@mail.corp.om failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	...cal/Cellar/imapfilter/2.5.7/share/imapfilter/account.lua:68: in function '_check_result'
	...cal/Cellar/imapfilter/2.5.7/share/imapfilter/account.lua:84: in function '_login_user'
	...cal/Cellar/imapfilter/2.5.7/share/imapfilter/account.lua:46: in function <...cal/Cellar/imapfilter/2.5.7/share/imapfilter/account.lua:15>
	(...tail calls...)
	/Users/max/.imapfilter/config.lua:74: in main chunk
```

running with -v (verbose) reveals nothing besides this.

Any ideas ?

**Comment by maxandersen** [comment]
to see if osx specific I tried using https://registry.hub.docker.com/u/ka2er/imapfilter/ and it has the same error.

**Comment by lefcha** [comment]
This looks like a server error during the authentication process.  First can you try running imapfilter with something like: `imapfilter -d /tmp/imapfilter.out` so we can see whether there are more details in the output file.

Next, can you connect through a terminal to your mail server with one of the following methods, issue the `CAPABILITY` request, and let me know of the results:

```
$ telnet <your-mail-server> 143
1 CAPABILITY
```

Or with:

```
$ openssl s_client -host <your-mail-server> -port 993 -crlf
1 CAPABILITY
```

If you can't issue the above commands, you can give me the mail server hostname, so I can see this info myself.

**Comment by maxandersen** [comment]
-d gives nothing. just empty file.

it does not respond on 143.

on 993 (I use ssl3 btw.) I get:

"CONNECTED(00000003)
depth=1 /C=US/ST=North Carolina/L=Raleigh/O=Red Hat, Inc./OU=IS/CN=Red Hat IS CA/emailAddress=sysadmin-rdu@redhat.com
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/C=US/ST=North Carolina/O=Red Hat, Inc./OU=Information Technology/CN=mail.corp.redhat.com/emailAddress=servicedesk@redhat.com
   i:/C=US/ST=North Carolina/L=Raleigh/O=Red Hat, Inc./OU=IS/CN=Red Hat IS CA/emailAddress=sysadmin-rdu@redhat.com
 1 s:/C=US/ST=North Carolina/L=Raleigh/O=Red Hat, Inc./OU=IS/CN=Red Hat IS CA/emailAddress=sysadmin-rdu@redhat.com
   i:/C=US/ST=North Carolina/L=Raleigh/O=Red Hat, Inc./OU=IS/CN=Red Hat IS CA/emailAddress=sysadmin-rdu@redhat.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIJpjCCCQ+gAwIBAgICCNswDQYJKoZIhvcNAQEFBQAwgZ0xCzAJBgNVBAYTAlVT
MRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBxMHUmFsZWlnaDEWMBQG
A1UEChMNUmVkIEhhdCwgSW5jLjELMAkGA1UECxMCSVMxFjAUBgNVBAMTDVJlZCBI
YXQgSVMgQ0ExJjAkBgkqhkiG9w0BCQEWF3N5c2FkbWluLXJkdUByZWRoYXQuY29t
MB4XDTEzMDYyODA5MjEyMloXDTE1MDYyODA5MjEyMlowgaUxCzAJBgNVBAYTAlVT
MRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEWMBQGA1UEChMNUmVkIEhhdCwgSW5j
LjEfMB0GA1UECxMWSW5mb3JtYXRpb24gVGVjaG5vbG9neTEdMBsGA1UEAxMUbWFp
bC5jb3JwLnJlZGhhdC5jb20xJTAjBgkqhkiG9w0BCQEWFnNlcnZpY2VkZXNrQHJl
ZGhhdC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEzmLPEI/N
sVQzP4JNW5VLsyNNOZ18lQV2aaLySi2CpOC78UEPMfgyNVkCAereZ9C/HfapVu6L
P4IlMuf77nhyXN6qSxBA9Yxc0zytKmjvN4MzGVR+o+Fuc3u+fL+ShwA3bDErF98m
X5Ekh4fBi+IJwxy89fILXypECib1YyxapItS0zveVT9bKhRKiYvpl/JaYVkM0by+
RVhGyCIHpWHk9v3FjbmTMjAhQIUiP1gBzcIAas8yl2HFNl2ndHtuxVLf+7YE32gJ
RxOS2+d1yClC7q0ny711ichpKS1fmZjsmsfKRXUF8+MPy2ZxzoTKGUBUCFEoiA1/
cAnXbn7uPnAtAgMBAAGjggZlMIIGYTCCBl0GA1UdEQSCBlQwggZQghRtYWlsLmNv
cnAucmVkaGF0LmNvbYIYY2FsZW5kYXIuY29ycC5yZWRoYXQuY29tgid6bWFpbDAx
LmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CJ3ptYWlsMDIuY29sbGFi
LnByb2QuaW50LnBoeDIucmVkaGF0LmNvbYInem1haWwwMy5jb2xsYWIucHJvZC5p
bnQucGh4Mi5yZWRoYXQuY29tgid6bWFpbDA0LmNvbGxhYi5wcm9kLmludC5waHgy
LnJlZGhhdC5jb22CJ3ptYWlsMDUuY29sbGFiLnByb2QuaW50LnBoeDIucmVkaGF0
LmNvbYInem1haWwwNi5jb2xsYWIucHJvZC5pbnQucGh4Mi5yZWRoYXQuY29tgid6
bWFpbDA3LmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CJ3ptYWlsMDgu
Y29sbGFiLnByb2QuaW50LnBoeDIucmVkaGF0LmNvbYInem1haWwwOS5jb2xsYWIu
cHJvZC5pbnQucGh4Mi5yZWRoYXQuY29tgid6bWFpbDEwLmNvbGxhYi5wcm9kLmlu
dC5waHgyLnJlZGhhdC5jb22CJ3ptYWlsMTEuY29sbGFiLnByb2QuaW50LnBoeDIu
cmVkaGF0LmNvbYInem1haWwxMi5jb2xsYWIucHJvZC5pbnQucGh4Mi5yZWRoYXQu
Y29tgid6bWFpbDEzLmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CJ3pt
YWlsMTQuY29sbGFiLnByb2QuaW50LnBoeDIucmVkaGF0LmNvbYInem1haWwxNS5j
b2xsYWIucHJvZC5pbnQucGh4Mi5yZWRoYXQuY29tgid6bWFpbDE2LmNvbGxhYi5w
cm9kLmludC5waHgyLnJlZGhhdC5jb22CJ3ptYWlsMTcuY29sbGFiLnByb2QuaW50
LnBoeDIucmVkaGF0LmNvbYInem1haWwxOC5jb2xsYWIucHJvZC5pbnQucGh4Mi5y
ZWRoYXQuY29tgid6bWFpbDE5LmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5j
b22CJ3ptYWlsMjAuY29sbGFiLnByb2QuaW50LnBoeDIucmVkaGF0LmNvbYInem1h
aWwyMS5jb2xsYWIucHJvZC5pbnQucGh4Mi5yZWRoYXQuY29tgid6bWFpbDIyLmNv
bGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CJ3ptYWlsMjMuY29sbGFiLnBy
b2QuaW50LnBoeDIucmVkaGF0LmNvbYInem1haWwyNC5jb2xsYWIucHJvZC5pbnQu
cGh4Mi5yZWRoYXQuY29tgid6bWFpbDI1LmNvbGxhYi5wcm9kLmludC5waHgyLnJl
ZGhhdC5jb22CJ3ptYWlsMjYuY29sbGFiLnByb2QuaW50LnBoeDIucmVkaGF0LmNv
bYInem1haWwyNy5jb2xsYWIucHJvZC5pbnQucGh4Mi5yZWRoYXQuY29tgid6bWFp
bDI4LmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CJ3ptYWlsMjkuY29s
bGFiLnByb2QuaW50LnBoeDIucmVkaGF0LmNvbYInem1haWwzMC5jb2xsYWIucHJv
ZC5pbnQucGh4Mi5yZWRoYXQuY29tgidhZG1pbjAxLmNvbGxhYi5wcm9kLmludC5w
aHgyLnJlZGhhdC5jb22CJ2FkbWluMDIuY29sbGFiLnByb2QuaW50LnBoeDIucmVk
aGF0LmNvbYIqemFyY2hpdmUwMS5jb2xsYWIucHJvZC5pbnQucGh4Mi5yZWRoYXQu
Y29tgip6YXJjaGl2ZTAyLmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22C
KHpwcm94eTAxLmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CKHpwcm94
eTAyLmNvbGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CKHpwcm94eTAzLmNv
bGxhYi5wcm9kLmludC5waHgyLnJlZGhhdC5jb22CKHpwcm94eTA0LmNvbGxhYi5w
cm9kLmludC5waHgyLnJlZGhhdC5jb20wDQYJKoZIhvcNAQEFBQADgYEAdizKs6uo
adNY/eMj0oFXp18Llm4wEORieXOr7I2bfJ7ZJf+N3iPBgGAGMA/mTRdGBNwySnhp
UgaaUDDJuhEBuXBIlAwukES76zRmgf+tKqugcJG7WnRqUS2YlIqIiB6gAlcV01gH
TijAgF8mMDd3XjCSGo+hL2hvJcVsg1uPCJ8=
-----END CERTIFICATE-----
subject=/C=US/ST=North Carolina/O=Red Hat, Inc./OU=Information Technology/CN=mail.corp.redhat.com/emailAddress=servicedesk@redhat.com
issuer=/C=US/ST=North Carolina/L=Raleigh/O=Red Hat, Inc./OU=IS/CN=Red Hat IS CA/emailAddress=sysadmin-rdu@redhat.com
---
No client certificate CA names sent
---
SSL handshake has read 4124 bytes and written 328 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID: FCA13CF8F9B213F8254F4533B10E701B488EFB8819E7F5340875979F5E787D11
    Session-ID-ctx:
    Master-Key: F1BFD27A6D1359B3F097A108BE31D6226100B1727DECA9DDF0D8A1269A2FE22776F407D8B8E89E0F34165716E590B727
    Key-Arg   : None
    Start Time: 1425420667
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
* OK IMAP4 ready"

btw. it works on my old linux box.

i'm wondering if there are some updates to SSL layers that causes some incompatibility.

the server is behind VPN so you won't be able to access it though.

**Comment by lefcha** [comment]
After you get the `OK IMAP4 ready`, what do you get when you issue the `1 CAPABILITY` command?

If it works on an older linux box, probably it's not the server or imapfilter, but some SSL issue as you mention.  What OpenSSL library versions do your old and current machines have?

**Comment by maxandersen** [comment]
I was guessing on openssl library issues. 

how do I check which version of openssl ?

**Comment by maxandersen** [comment]
so I recompiled - now it works. Yeah, I guess openssl libraries changed.
