### ISSUE TITLE
SSL issue on apple?

### ISSUE THREAD

**Issue by markgiesbrecht** [lefcha/imapfilter#91]
Hi,

First, great software!  Thank you.

For the past couple of weeks I've been having an issue connecting to some IMAP accounts.  Using IMAPFilter 2.5.7, get the following error where there was none before.  I have confirmed that the password being used is correct.

imapfilter: initiating SSL connection to mailservices.uwaterloo.ca; error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
imapfilter: login request to cs-direc@mailservices.uwaterloo.ca failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/usr/local/share/imapfilter/account.lua:68: in function '_check_result'
	/usr/local/share/imapfilter/account.lua:84: in function '_login_user'
	/usr/local/share/imapfilter/account.lua:46: in function 'IMAP'
	/Users/mwg/.imapfilter/config.lua:123: in main chunk

**Comment by Papafox** [comment]
Sounds like OpenSSL is telling you it no longer supports SSLv3

Try using ssl = 'tls12' in IMAP()

**Comment by lefcha** [comment]
Has this issue been solved by trying another SSL/TLS protocol, or does it need further investigation?
