### ISSUE TITLE
Getting password from OSX keychain

### ISSUE THREAD

**Issue by larryhynes** [lefcha/imapfilter#98]
I don't like having passwords in plain text config files, so I wanted to see if it was possible – on OSX – to grab the password from the user's keychain. I had no luck using `pipe_from` but, using the example command from [mbsync's example config](http://sourceforge.net/p/isync/isync/ci/760bfa2cc66d30d6bb6272d55f82874c8fb0c0ae/tree/src/mbsyncrc.sample), i was able to get it working using the following:

```lua
pass = io.popen('/usr/bin/security find-internet-password -w -a USERNAME -s IMAPSERVER ~/Library/Keychains/login.keychain'
res = pass:read("*a")
res = string.gsub(res, "\n", "")

foo = IMAP {
  server = 'mail.foo.com',
  username = 'user',
  password = res
}
```

As I know _zero_ lua, I'm sure there's a nicer, more idiomatic, way of handling this but it's nice to know that it's possible.

Would you have any interest in adding support and examples of password input from the system's keychain?

**Comment by larryhynes** [comment]
I guess not.

**Comment by lmoellendorf** [comment]
> I had no luck using `pipe_from` but, ...

I got it working like this:

```lua
status, passwd = pipe_from('pass mail/my_account')
passwd = string.gsub(passwd, "\n", "")

hermesRemote = IMAP {
    server = 'mail.foo.com',
    username = 'user',
    password = passwd,
}
```
The magical part is `passwd = string.gsub(passwd, "\n", "")` which I only found out thanks to your comment.
